/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => HeptaCardPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// storage.ts
var import_obsidian = require("obsidian");

// types.ts
var DEFAULT_SETTINGS = {
  cardsFolder: "_CardBox/Cards",
  boxesFolder: "_CardBox/Boxes",
  boxes: [],
  defaultBoxId: "",
  cardWidth: 320,
  cardHeight: 220,
  previewSmallScale: 100,
  previewMediumScale: 100,
  previewLargeScale: 100,
  previewTitleSize: 23,
  sortMode: "created-desc",
  showInfoPanel: true,
  embedStyle: "card",
  lazyLoad: true,
  folderHidingEnabled: false,
  hiddenFolderPaths: []
};
var CARD_FILE_PREFIX = "CardBox";
var CARD_BLOCK_TYPE = "cardbox";

// storage.ts
var LEGACY_CARDS_FOLDER = "_HeptaCards";
var LEGACY_CARD_FILE_PREFIX = "HeptaCard";
var HeptaCardStorage = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  async ensureFolders() {
    await this.ensureFolder(this.settings.cardsFolder);
    await this.ensureFolder(this.settings.boxesFolder);
  }
  async ensureFolder(path) {
    const normalized = (0, import_obsidian.normalizePath)(path);
    const existing = this.app.vault.getFolderByPath(normalized);
    if (!existing) {
      await this.app.vault.createFolder(normalized);
    }
  }
  getCardFolderPath(boxId) {
    return (0, import_obsidian.normalizePath)(`${this.settings.cardsFolder}/${boxId}`);
  }
  async ensureCardFolder(boxId) {
    await this.ensureFolder(this.getCardFolderPath(boxId));
  }
  createBoxRecord(name, description = "", color) {
    const now = Date.now();
    return {
      id: this.makeId("box"),
      name,
      description,
      color,
      created: now,
      updated: now
    };
  }
  async createCard(box, title, content = "", tags = [], color) {
    await this.ensureCardFolder(box.id);
    const now = Date.now();
    const id = this.makeId("card");
    const filePath = this.getAvailableCardPath(box.id, title);
    const initialContent = content.trim() || `# ${title}

`;
    const body = this.renderCardFile({
      id,
      title,
      boxId: box.id,
      boxName: box.name,
      filePath,
      created: now,
      updated: now,
      tags,
      color
    }, initialContent);
    const file = await this.app.vault.create(filePath, body);
    return this.readCardRecord(file);
  }
  async updateCardFile(card, content, patch) {
    const file = this.app.vault.getFileByPath(card.filePath);
    if (!file)
      return null;
    const next = {
      ...card,
      ...patch,
      updated: Date.now()
    };
    const body = this.renderCardFile(next, content);
    await this.app.vault.modify(file, body);
    return this.readCardRecord(file);
  }
  async deleteCard(card) {
    const file = this.app.vault.getFileByPath(card.filePath);
    if (file) {
      await this.app.vault.delete(file, true);
    }
  }
  async readAllCards() {
    var _a;
    const files = this.app.vault.getFiles().filter((file) => this.isCardFile(file));
    const cards = [];
    for (const file of files) {
      const card = await this.readCardRecord(file);
      if (!card)
        continue;
      const normalized = (_a = await this.normalizeLegacyCardPath(file, card)) != null ? _a : card;
      await this.cleanLegacyFrontmatter(normalized);
      cards.push(normalized);
    }
    return cards;
  }
  async readCardRecord(file) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j;
    const text = await this.app.vault.cachedRead(file);
    const frontmatter = this.getFrontmatter(text);
    const inCardsFolder = this.isInCardFolder(file.path);
    if (!inCardsFolder && (!frontmatter || !frontmatter.hcard))
      return null;
    const cache = this.app.metadataCache.getFileCache(file);
    const fm = frontmatter != null ? frontmatter : {};
    const body = this.stripFrontmatter(text);
    const boxId = (_b = (_a = fm.hcard_box) != null ? _a : this.getBoxIdFromPath(file.path)) != null ? _b : this.settings.defaultBoxId;
    const box = this.settings.boxes.find((item) => item.id === boxId);
    return {
      id: (_c = fm.hcard_id) != null ? _c : this.stableCardId(file.path),
      title: (_e = (_d = fm.title) != null ? _d : this.readFirstHeading(body)) != null ? _e : this.cleanDisplayTitle(file.basename.replace(/^(?:HeptaCard|CardBox)\s*/i, "")) || file.basename,
      boxId,
      boxName: (_f = box == null ? void 0 : box.name) != null ? _f : "Unsorted",
      filePath: file.path,
      created: (_g = this.parseDate(fm.hcard_created)) != null ? _g : file.stat.ctime,
      updated: (_h = this.parseDate(fm.hcard_updated)) != null ? _h : file.stat.mtime,
      tags: this.normalizeTags([
        ...(_i = fm.hcard_tags) != null ? _i : [],
        ...this.readTags((_j = cache == null ? void 0 : cache.tags) != null ? _j : []),
        ...this.readFrontmatterTags(fm.tags)
      ]),
      color: fm.hcard_color,
      width: void 0,
      height: void 0,
      pinned: false
    };
  }
  readCardContent(file) {
    return this.app.vault.cachedRead(file).then((text) => this.stripFrontmatter(text));
  }
  async getCardBody(file) {
    const text = await this.app.vault.cachedRead(file);
    return this.stripFrontmatter(text);
  }
  async getCardFile(card) {
    return this.app.vault.getFileByPath(card.filePath);
  }
  getCardByPath(path, cards) {
    var _a;
    return (_a = cards.find((card) => card.filePath === path)) != null ? _a : null;
  }
  async collectReferences(card) {
    const refs = /* @__PURE__ */ new Map();
    const cardFile = this.app.vault.getFileByPath(card.filePath);
    const resolved = this.app.metadataCache.resolvedLinks;
    for (const [sourcePath, destinations] of Object.entries(resolved)) {
      if (sourcePath === card.filePath)
        continue;
      if (!destinations || !Object.prototype.hasOwnProperty.call(destinations, card.filePath))
        continue;
      const file = this.app.vault.getFileByPath(sourcePath);
      if (!file)
        continue;
      refs.set(sourcePath, await this.buildReferenceFromFile(file, card, cardFile));
    }
    return Array.from(refs.values()).sort((a, b) => a.noteTitle.localeCompare(b.noteTitle, "zh-Hans-CN"));
  }
  async collectBacklinks(card) {
    return this.collectReferences(card);
  }
  async ensureBoxFolder(box) {
    await this.ensureCardFolder(box.id);
  }
  renderCardFile(card, body) {
    return `${body.trim()}
`;
  }
  getFrontmatter(text) {
    var _a;
    const match = text.match(/^---\s*\n([\s\S]*?)\n---\s*\n?/);
    if (!match)
      return null;
    return (_a = (0, import_obsidian.parseYaml)(match[1])) != null ? _a : {};
  }
  stripFrontmatter(text) {
    return text.replace(/^---\s*\n[\s\S]*?\n---\s*\n?/, "");
  }
  async writeCard(card, body) {
    const file = this.app.vault.getFileByPath(card.filePath);
    if (!file)
      return;
    const next = {
      ...card,
      updated: Date.now()
    };
    await this.app.vault.modify(file, this.renderCardFile(next, body));
  }
  async updateCardMeta(card, patch) {
    const file = this.app.vault.getFileByPath(card.filePath);
    if (!file)
      return null;
    const body = await this.getCardBody(file);
    const next = {
      ...card,
      ...patch,
      updated: Date.now()
    };
    await this.app.vault.modify(file, this.renderCardFile(next, body));
    return this.readCardRecord(file);
  }
  async renameCardFile(card, newTitle) {
    const file = this.app.vault.getFileByPath(card.filePath);
    if (!file)
      return null;
    const newPath = this.getAvailableCardPath(card.boxId, newTitle, file.path);
    if (newPath !== file.path) {
      await this.app.fileManager.renameFile(file, newPath);
    }
    const renamed = this.app.vault.getFileByPath(newPath);
    return renamed ? this.readCardRecord(renamed) : null;
  }
  async moveCardToBox(card, box) {
    const file = this.app.vault.getFileByPath(card.filePath);
    if (!file)
      return null;
    await this.ensureCardFolder(box.id);
    const newPath = this.getAvailableCardPath(box.id, card.title, file.path);
    await this.app.fileManager.renameFile(file, newPath);
    return this.readCardRecord(this.app.vault.getFileByPath(newPath));
  }
  async loadBoxesFromFolder() {
    var _a, _b;
    const folder = this.app.vault.getFolderByPath(this.settings.boxesFolder);
    if (!folder)
      return [];
    const files = this.app.vault.getFiles().filter((file) => file.path.startsWith(folder.path));
    const boxes = [];
    for (const file of files) {
      const data = await this.app.vault.cachedRead(file);
      const fm = this.getFrontmatter(data);
      if (fm && fm.hcard && fm.hcard_id && fm.title) {
        boxes.push({
          id: fm.hcard_id,
          name: fm.title,
          description: "",
          created: (_a = this.parseDate(fm.hcard_created)) != null ? _a : file.stat.ctime,
          updated: (_b = this.parseDate(fm.hcard_updated)) != null ? _b : file.stat.mtime
        });
      }
    }
    return boxes;
  }
  isCardFile(file) {
    return this.isInCardFolder(file.path) || file.basename.startsWith(CARD_FILE_PREFIX) || file.basename.startsWith(LEGACY_CARD_FILE_PREFIX);
  }
  isInCardFolder(path) {
    const normalized = (0, import_obsidian.normalizePath)(path);
    return normalized.startsWith((0, import_obsidian.normalizePath)(`${this.settings.cardsFolder}/`)) || normalized.startsWith((0, import_obsidian.normalizePath)(`${LEGACY_CARDS_FOLDER}/`));
  }
  parseDate(value) {
    if (!value)
      return null;
    const parsed = new Date(value).getTime();
    return Number.isFinite(parsed) ? parsed : null;
  }
  formatDate(ts) {
    return new Date(ts).toISOString();
  }
  readTags(tags) {
    return tags.map((item) => item.tag.replace(/^#/, ""));
  }
  readFrontmatterTags(value) {
    if (Array.isArray(value))
      return value.map(String);
    if (typeof value === "string")
      return value.split(/[,\s]+/);
    return [];
  }
  normalizeTags(tags) {
    return Array.from(new Set(tags.flatMap((tag) => tag.split(/[,\s]+/)).map((tag) => tag.trim().replace(/^#/, "")).filter(Boolean)));
  }
  async buildReferenceFromFile(file, card, cardFile) {
    const text = await this.app.vault.cachedRead(file);
    const lines = text.split(/\r?\n/);
    const lineIndex = this.findReferenceLine(lines, card, cardFile);
    return {
      notePath: file.path,
      noteTitle: this.cleanDisplayTitle(file.basename),
      lineNumber: lineIndex >= 0 ? lineIndex + 1 : void 0,
      context: lineIndex >= 0 ? this.buildContext(lines, lineIndex) : void 0
    };
  }
  async findTextReference(file, card, cardFile) {
    const text = await this.app.vault.cachedRead(file);
    const lines = text.split(/\r?\n/);
    const lineIndex = this.findReferenceLine(lines, card, cardFile);
    if (lineIndex < 0)
      return null;
    return {
      notePath: file.path,
      noteTitle: this.cleanDisplayTitle(file.basename),
      lineNumber: lineIndex + 1,
      context: this.buildContext(lines, lineIndex)
    };
  }
  findReferenceLine(lines, card, cardFile) {
    const variants = this.linkVariants(card, cardFile);
    for (let i = 0; i < lines.length; i++) {
      if (variants.some((variant) => variant.test(lines[i])))
        return i;
    }
    return -1;
  }
  linkVariants(card, cardFile) {
    const values = /* @__PURE__ */ new Set();
    const pathNoExt = card.filePath.replace(/\.md$/i, "");
    values.add(new RegExp(`!\\[\\[${this.escapeRegExp(card.filePath)}(?:\\|[^\\]]*)?\\]\\]`, "i"));
    values.add(new RegExp(`!\\[\\[${this.escapeRegExp(pathNoExt)}(?:\\|[^\\]]*)?\\]\\]`, "i"));
    values.add(new RegExp(`\\[\\[${this.escapeRegExp(card.filePath)}(?:\\|[^\\]]*)?\\]\\]`, "i"));
    values.add(new RegExp(`\\[\\[${this.escapeRegExp(pathNoExt)}(?:\\|[^\\]]*)?\\]\\]`, "i"));
    if (cardFile) {
      const linkText = this.app.metadataCache.fileToLinktext(cardFile, "", true);
      values.add(new RegExp(`!\\[\\[${this.escapeRegExp(cardFile.basename)}(?:\\|[^\\]]*)?\\]\\]`, "i"));
      values.add(new RegExp(`\\[\\[${this.escapeRegExp(cardFile.basename)}(?:\\|[^\\]]*)?\\]\\]`, "i"));
      values.add(new RegExp(`!\\[\\[${this.escapeRegExp(linkText)}(?:\\|[^\\]]*)?\\]\\]`, "i"));
      values.add(new RegExp(`\\[\\[${this.escapeRegExp(linkText)}(?:\\|[^\\]]*)?\\]\\]`, "i"));
    }
    return Array.from(values);
  }
  buildContext(lines, index) {
    const start = Math.max(0, index - 1);
    const end = Math.min(lines.length, index + 2);
    return lines.slice(start, end).join("\n").trim();
  }
  makeId(prefix) {
    return `${prefix}_${Math.random().toString(36).slice(2, 9)}_${Date.now().toString(36)}`;
  }
  getAvailableCardPath(boxId, title, currentPath) {
    const folder = this.getCardFolderPath(boxId);
    const base = this.slug(title);
    let candidate = (0, import_obsidian.normalizePath)(`${folder}/${base}.md`);
    let index = 2;
    while (candidate !== currentPath && this.app.vault.getFileByPath(candidate)) {
      candidate = (0, import_obsidian.normalizePath)(`${folder}/${base}-${index}.md`);
      index += 1;
    }
    return candidate;
  }
  async normalizeLegacyCardPath(file, card) {
    const cleanBase = this.slug(card.title);
    const legacyPrefix = `${cleanBase}-`;
    if (!file.basename.startsWith(legacyPrefix))
      return null;
    const suffix = file.basename.slice(legacyPrefix.length);
    if (!/^[a-z0-9_]{4,}$/i.test(suffix))
      return null;
    const nextPath = this.getAvailableCardPath(card.boxId, card.title, file.path);
    if (nextPath === file.path)
      return null;
    await this.app.fileManager.renameFile(file, nextPath);
    const renamed = this.app.vault.getFileByPath(nextPath);
    return renamed ? this.readCardRecord(renamed) : null;
  }
  async cleanLegacyFrontmatter(card) {
    const file = this.app.vault.getFileByPath(card.filePath);
    if (!file)
      return;
    const text = await this.app.vault.cachedRead(file);
    if (!this.getFrontmatter(text))
      return;
    const body = this.stripFrontmatter(text).trim();
    await this.app.vault.modify(file, `${body}
`);
  }
  compactFrontmatter(data) {
    return Object.fromEntries(Object.entries(data).filter(([, value]) => {
      if (Array.isArray(value))
        return value.length > 0;
      return value !== void 0 && value !== null && value !== "";
    }));
  }
  slug(title) {
    const clean = title.toLowerCase().replace(/[^\w\u4e00-\u9fa5]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 48);
    return clean || CARD_FILE_PREFIX;
  }
  cleanDisplayTitle(fileName) {
    return fileName.replace(/-[a-z0-9_]{4,}$/i, "").replace(/-+$/g, "");
  }
  escapeRegExp(value) {
    return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  }
  getBoxIdFromPath(path) {
    const normalized = (0, import_obsidian.normalizePath)(path);
    const root = normalized.startsWith((0, import_obsidian.normalizePath)(`${this.settings.cardsFolder}/`)) ? (0, import_obsidian.normalizePath)(this.settings.cardsFolder) : (0, import_obsidian.normalizePath)(LEGACY_CARDS_FOLDER);
    const relative = normalized.slice(root.length + 1);
    const first = relative.split("/")[0];
    if (!first || first.endsWith(".md"))
      return null;
    return first;
  }
  readFirstHeading(body) {
    const line = body.split(/\r?\n/).find((item) => /^#\s+\S/.test(item.trim()));
    return (line == null ? void 0 : line.replace(/^#\s+/, "").trim()) || null;
  }
  stableCardId(path) {
    let hash = 2166136261;
    for (let i = 0; i < path.length; i++) {
      hash ^= path.charCodeAt(i);
      hash = Math.imul(hash, 16777619);
    }
    return `card_${(hash >>> 0).toString(36)}`;
  }
};

// embed.ts
var import_obsidian2 = require("obsidian");
var HeptaCardEmbedRenderer = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  async process(el, ctx) {
    var _a, _b;
    const embedEls = Array.from(el.querySelectorAll(".internal-embed, .markdown-embed"));
    for (const embedEl of embedEls) {
      const src = (_b = (_a = embedEl.getAttribute("src")) != null ? _a : embedEl.dataset.src) != null ? _b : "";
      const file = this.resolveEmbed(src, ctx.sourcePath);
      if (!file)
        continue;
      if (!this.plugin.storage.isCardFile(file))
        continue;
      if (file.path === ctx.sourcePath) {
        this.renderLoopGuard(embedEl);
        continue;
      }
      const child = new HeptaCardEmbedChild(embedEl, this.plugin, file, ctx.sourcePath);
      ctx.addChild(child);
      child.load();
    }
  }
  resolveEmbed(src, sourcePath) {
    if (!src)
      return null;
    const withoutBlock = src.split("#")[0].split("|")[0];
    const byPath = this.plugin.app.vault.getFileByPath(withoutBlock);
    if (byPath)
      return byPath;
    return this.plugin.app.metadataCache.getFirstLinkpathDest(withoutBlock, sourcePath);
  }
  renderLoopGuard(el) {
    el.empty();
    el.addClass("heptacard-loop-guard");
    el.createEl("strong", { text: "\u5DF2\u963B\u6B62\u5FAA\u73AF\u5D4C\u5957" });
    el.createEl("p", { text: "\u8FD9\u5F20\u5361\u7247\u6B63\u5728\u5C1D\u8BD5\u5D4C\u5165\u81EA\u5DF1\u6216\u5F62\u6210\u9012\u5F52\u5FAA\u73AF\u3002" });
  }
  async renderInto(container, file, sourcePath, compact = false) {
    const card = await this.plugin.storage.readCardRecord(file);
    if (!card)
      return;
    const body = await this.plugin.storage.getCardBody(file);
    await renderHeptaCard(this.plugin, container, card, body, sourcePath, {
      compact,
      editable: true,
      showInfo: this.plugin.settings.showInfoPanel
    });
  }
};
var HeptaCardEmbedChild = class extends import_obsidian2.MarkdownRenderChild {
  constructor(containerEl, plugin, file, sourcePath) {
    super(containerEl);
    this.plugin = plugin;
    this.file = file;
    this.sourcePath = sourcePath;
  }
  async onload() {
    this.containerEl.empty();
    this.containerEl.addClass("heptacard-embed-shell");
    if (this.file.path === this.sourcePath) {
      this.containerEl.createEl("div", {
        cls: "heptacard-loop-guard",
        text: "\u5DF2\u963B\u6B62\u5361\u7247\u9012\u5F52\u5D4C\u5165\u3002"
      });
      return;
    }
    const visible = await this.waitUntilVisible();
    if (!visible)
      return;
    await this.plugin.embedRenderer.renderInto(this.containerEl, this.file, this.sourcePath);
  }
  waitUntilVisible() {
    if (!this.plugin.settings.lazyLoad || !("IntersectionObserver" in window)) {
      return Promise.resolve(true);
    }
    return new Promise((resolve) => {
      const observer = new IntersectionObserver((entries) => {
        if (entries.some((entry) => entry.isIntersecting)) {
          observer.disconnect();
          resolve(true);
        }
      }, { rootMargin: "480px 0px" });
      observer.observe(this.containerEl);
      this.register(() => observer.disconnect());
    });
  }
};
async function renderHeptaCard(plugin, container, card, body, sourcePath, options = {}) {
  container.empty();
  container.addClass("heptacard-card");
  container.toggleClass("is-compact", !!options.compact);
  if (card.color)
    container.style.setProperty("--heptacard-accent", card.color);
  const toolbar = container.createDiv({ cls: "heptacard-card-toolbar" });
  toolbar.createDiv({ cls: "heptacard-card-title", text: card.title });
  const actions = toolbar.createDiv({ cls: "heptacard-card-actions" });
  const openButton = actions.createEl("button", { cls: "clickable-icon heptacard-icon-button", attr: { "aria-label": "\u5C55\u5F00\u5361\u7247" } });
  (0, import_obsidian2.setIcon)(openButton, "maximize-2");
  openButton.addEventListener("click", (event) => {
    event.stopPropagation();
    void plugin.openWorkbenchForCard(card);
  });
  const fileButton = actions.createEl("button", { cls: "clickable-icon heptacard-icon-button", attr: { "aria-label": "\u6253\u5F00\u6E90\u6587\u4EF6" } });
  (0, import_obsidian2.setIcon)(fileButton, "file-text");
  fileButton.addEventListener("click", async (event) => {
    event.stopPropagation();
    await plugin.app.workspace.openLinkText(card.filePath, sourcePath, false);
  });
  const content = container.createDiv({ cls: "heptacard-card-content" });
  const view = content.createDiv({ cls: "heptacard-markdown-view" });
  const component = new import_obsidian2.Component();
  component.load();
  await import_obsidian2.MarkdownRenderer.render(plugin.app, body, view, card.filePath, component);
  if (options.showInfo) {
    await renderInfoPanel(plugin, container, card);
  }
}
async function renderInfoPanel(plugin, container, card) {
  const panel = container.createEl("details", { cls: "heptacard-info-panel", attr: { open: "true" } });
  const summary = panel.createEl("summary", { cls: "heptacard-info-summary" });
  const summaryTitle = summary.createSpan({ cls: "heptacard-info-summary-title" });
  (0, import_obsidian2.setIcon)(summaryTitle.createSpan(), "info");
  summaryTitle.createSpan({ text: "Info" });
  summary.createSpan({ cls: "heptacard-info-count", text: "Hide" });
  const cardFile = plugin.app.vault.getFileByPath(card.filePath);
  if (!cardFile)
    return;
  const body = await plugin.storage.getCardBody(cardFile);
  const stats = countText(body);
  const grid = panel.createDiv({ cls: "heptacard-info-grid" });
  renderInfoRow(grid, "clock-3", "\u521B\u5EFA\u65F6\u95F4", new Date(card.created).toLocaleDateString());
  renderInfoRow(grid, "clock", "\u66F4\u65B0\u65F6\u95F4", new Date(card.updated).toLocaleDateString());
  renderCountRow(grid, stats.words, stats.chars);
  const backlinks = panel.createDiv({ cls: "heptacard-backlinks" });
  const refs = await plugin.storage.collectBacklinks(card);
  const heading = backlinks.createDiv({ cls: "heptacard-info-section-title" });
  (0, import_obsidian2.setIcon)(heading.createSpan(), "corner-down-left");
  heading.createSpan({ text: `\u53CD\u5411\u94FE\u63A5 (${refs.length})` });
  renderBacklinks(plugin, backlinks, refs);
  const boards = panel.createDiv({ cls: "heptacard-info-bottom" });
  const boardLabel = boards.createDiv({ cls: "heptacard-info-bottom-label" });
  (0, import_obsidian2.setIcon)(boardLabel.createSpan(), "map");
  boardLabel.createSpan({ text: "\u6240\u5728\u5361\u7247\u76D2 (1)" });
  const boardValue = boards.createDiv({ cls: "heptacard-info-bottom-value" });
  (0, import_obsidian2.setIcon)(boardValue.createSpan(), "map");
  boardValue.createSpan({ text: card.boxName });
  const tagLine = panel.createDiv({ cls: "heptacard-info-bottom" });
  const tagLabel = tagLine.createDiv({ cls: "heptacard-info-bottom-label" });
  (0, import_obsidian2.setIcon)(tagLabel.createSpan(), "hash");
  tagLabel.createSpan({ text: `\u6807\u7B7E (${card.tags.length})` });
  const tagValue = tagLine.createDiv({ cls: "heptacard-info-bottom-value heptacard-tag-row" });
  card.tags.forEach((tag) => tagValue.createSpan({ cls: "heptacard-tag", text: `#${tag}` }));
}
function renderInfoRow(container, icon, label, value) {
  const row = container.createDiv({ cls: "heptacard-info-row" });
  const labelEl = row.createDiv({ cls: "heptacard-info-label" });
  (0, import_obsidian2.setIcon)(labelEl.createSpan(), icon);
  labelEl.createSpan({ text: label });
  row.createDiv({ cls: "heptacard-info-value", text: value });
}
function renderCountRow(container, words, chars) {
  const row = container.createDiv({ cls: "heptacard-info-row" });
  const labelEl = row.createDiv({ cls: "heptacard-info-label" });
  (0, import_obsidian2.setIcon)(labelEl.createSpan(), "type");
  labelEl.createSpan({ text: "\u5B57\u6570" });
  const value = row.createDiv({ cls: "heptacard-info-value heptacard-count-value" });
  value.createSpan({ cls: "heptacard-count-number", text: String(words) });
  value.createSpan({ cls: "heptacard-count-unit", text: " \u8BCD" });
  value.createSpan({ cls: "heptacard-count-number", text: String(chars) });
  value.createSpan({ cls: "heptacard-count-unit", text: " \u5B57\u7B26" });
}
function renderBacklinks(plugin, container, refs) {
  if (!refs.length) {
    container.createDiv({ cls: "heptacard-muted", text: "\u8FD8\u6CA1\u6709\u7B14\u8BB0\u5F15\u7528\u8FD9\u5F20\u5361\u7247\u3002" });
    return;
  }
  refs.forEach((ref) => {
    var _a;
    const item = container.createEl("details", { cls: "heptacard-backlink" });
    const summary = item.createEl("summary", { cls: "heptacard-backlink-summary" });
    const chevron = summary.createSpan({ cls: "heptacard-backlink-chevron" });
    (0, import_obsidian2.setIcon)(chevron, "chevron-right");
    (0, import_obsidian2.setIcon)(summary.createSpan({ cls: "heptacard-backlink-file-icon" }), "file-text");
    summary.createSpan({ cls: "heptacard-backlink-title", text: cleanReferenceTitle(ref.noteTitle) });
    const summaryJump = summary.createEl("button", { cls: "clickable-icon heptacard-backlink-summary-jump", attr: { "aria-label": "\u8DF3\u8F6C\u5230\u5F15\u7528" } });
    (0, import_obsidian2.setIcon)(summaryJump, "arrow-right-circle");
    summaryJump.addEventListener("click", async (event) => {
      event.preventDefault();
      event.stopPropagation();
      await plugin.openReference(ref.notePath, ref.lineNumber);
    });
    const context = item.createDiv({ cls: "heptacard-backlink-context" });
    const text = context.createDiv({ cls: "heptacard-backlink-text" });
    text.setText(((_a = ref.context) == null ? void 0 : _a.trim()) || "\u6253\u5F00\u5F15\u7528\u4F4D\u7F6E");
    const jump = context.createEl("button", { cls: "clickable-icon heptacard-backlink-jump", attr: { "aria-label": "\u8DF3\u8F6C\u5230\u5F15\u7528" } });
    (0, import_obsidian2.setIcon)(jump, "arrow-right-circle");
    context.addEventListener("click", async () => {
      await plugin.openReference(ref.notePath, ref.lineNumber);
    });
  });
}
function cleanReferenceTitle(title) {
  return title.replace(/-[a-z0-9_]{4,}$/i, "").replace(/-+$/g, "");
}
function countText(text) {
  const clean = text.replace(/[#>*_`~\-[\]()!]/g, " ").trim();
  const words = clean ? clean.split(/\s+/).length : 0;
  const chars = clean.replace(/\s/g, "").length;
  return { words, chars };
}
var CardInsertModal = class extends import_obsidian2.FuzzySuggestModal {
  constructor(app, plugin, onChoose) {
    super(app);
    this.plugin = plugin;
    this.onChoose = onChoose;
    this.setPlaceholder("\u67E5\u627E\u5361\u7247...");
    this.emptyStateText = "\u6CA1\u6709\u627E\u5230\u5361\u7247";
  }
  getItems() {
    return this.plugin.cards;
  }
  getItemText(item) {
    return `${item.title} ${item.boxName} ${item.tags.join(" ")}`;
  }
  onChooseItem(item, _evt) {
    this.onChoose(item);
  }
};
var SlashCardSuggest = class extends import_obsidian2.EditorSuggest {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
    this.limit = 12;
  }
  onTrigger(cursor, editor, file) {
    var _a, _b;
    if (!file)
      return null;
    const line = editor.getLine(cursor.line).slice(0, cursor.ch);
    const match = line.match(/(?:^|\s)\/card\s*([^/]*)$/);
    if (!match)
      return null;
    const startCh = line.lastIndexOf("/card");
    return {
      start: { line: cursor.line, ch: startCh },
      end: cursor,
      query: (_b = (_a = match[1]) == null ? void 0 : _a.trim()) != null ? _b : ""
    };
  }
  getSuggestions(context) {
    return this.plugin.searchCards(context.query).slice(0, this.limit);
  }
  renderSuggestion(card, el) {
    el.addClass("heptacard-suggest-item");
    el.createDiv({ cls: "heptacard-suggest-title", text: card.title });
    el.createDiv({ cls: "heptacard-suggest-meta", text: `${card.boxName} / ${card.tags.map((tag) => `#${tag}`).join(" ")}` });
  }
  selectSuggestion(card, _evt) {
    const context = this.context;
    if (!context)
      return;
    context.editor.replaceRange(this.plugin.makeEmbed(card, context.file.path), context.start, context.end);
    new import_obsidian2.Notice(`\u5DF2\u63D2\u5165\uFF1A${card.title}`);
  }
};
function parseCardBlock(source) {
  var _a, _b;
  const trimmed = source.trim();
  if (!trimmed)
    return null;
  const pathMatch = trimmed.match(/^(?:path|file):\s*(.+)$/m);
  const idMatch = trimmed.match(/^id:\s*(.+)$/m);
  return {
    path: (_a = pathMatch == null ? void 0 : pathMatch[1]) == null ? void 0 : _a.trim(),
    id: (_b = idMatch == null ? void 0 : idMatch[1]) == null ? void 0 : _b.trim()
  };
}
async function renderCardBlock(plugin, source, el, ctx) {
  const parsed = parseCardBlock(source);
  if (!parsed) {
    el.createDiv({ cls: "heptacard-loop-guard", text: "\u65E0\u6548\u7684 cardbox \u5757\u3002" });
    return;
  }
  const card = plugin.cards.find((item) => item.id === parsed.id || item.filePath === parsed.path);
  if (!card) {
    el.createDiv({ cls: "heptacard-loop-guard", text: "\u672A\u627E\u5230\u5361\u7247\u3002" });
    return;
  }
  const file = plugin.app.vault.getFileByPath(card.filePath);
  if (!file)
    return;
  await plugin.embedRenderer.renderInto(el, file, ctx.sourcePath);
}
var CARD_BLOCK_LANGUAGE = CARD_BLOCK_TYPE;

// view.ts
var import_obsidian3 = require("obsidian");
var VIEW_TYPE_HEPTACARD = "heptacard-workbench";
var HeptaCardWorkbenchView = class extends import_obsidian3.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.selectedCardIds = /* @__PURE__ */ new Set();
    this.currentBoxId = "all";
    this.query = "";
    this.tagFilter = "";
    this.imageOnly = false;
    this.streamCollapsed = false;
    this.streamWidthPercent = 50;
    this.highlightedCardId = "";
    this.previewComponents = [];
    this.previewComponentByCard = /* @__PURE__ */ new Map();
    this.lastRenderedPreview = /* @__PURE__ */ new Map();
    this.previewSyncTimers = /* @__PURE__ */ new Map();
    this.renderTokens = /* @__PURE__ */ new Map();
    this.nativeMode = "live";
    this.previewSize = "medium";
    this.nativeEditors = /* @__PURE__ */ new Map();
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_HEPTACARD;
  }
  getDisplayText() {
    return "\u5361\u7247\u76D2";
  }
  getIcon() {
    return "layout-grid";
  }
  async onOpen() {
    await this.plugin.refreshCards();
    this.render();
  }
  onunload() {
    this.unloadNativeEditors();
    this.unloadPreviewComponents();
  }
  refresh() {
    if (this.nativeEditors.size > 0) {
      void this.refreshGridOnly();
      return;
    }
    this.render();
  }
  async revealCard(cardId) {
    this.highlightedCardId = cardId;
    const card = this.plugin.cards.find((item) => item.id === cardId);
    const needsFilterReset = !!card && (this.currentBoxId !== "all" && this.currentBoxId !== card.boxId || !!this.query.trim() || !!this.tagFilter.trim() || this.streamCollapsed);
    if (card && needsFilterReset) {
      this.currentBoxId = card.boxId;
      this.query = "";
      this.tagFilter = "";
      this.streamCollapsed = false;
      this.render();
    }
    window.setTimeout(() => {
      var _a, _b;
      this.contentEl.querySelectorAll(".is-highlighted, .is-revealed").forEach((el) => {
        el.removeClass("is-highlighted");
        el.removeClass("is-revealed");
      });
      const target = (_a = this.streamEl) == null ? void 0 : _a.querySelector(`[data-card-id="${cardId}"]`);
      const gridTarget = (_b = this.gridEl) == null ? void 0 : _b.querySelector(`[data-card-id="${cardId}"]`);
      gridTarget == null ? void 0 : gridTarget.addClass("is-revealed");
      if (!target)
        return;
      target.scrollIntoView({ block: "center", behavior: "smooth" });
      target.addClass("is-revealed");
      const host = target.querySelector(".heptacard-native-editor-host");
      if (host)
        void this.mountNativeEditor(cardId, host);
      window.setTimeout(() => {
        target.removeClass("is-revealed");
        gridTarget == null ? void 0 : gridTarget.removeClass("is-revealed");
      }, 1200);
    }, 80);
  }
  render() {
    this.unloadNativeEditors();
    this.unloadPreviewComponents();
    const container = this.contentEl;
    container.empty();
    container.addClass("heptacard-workbench");
    this.renderTopbar(container);
    if (this.selectedCardIds.size > 0)
      this.renderBulkBar(container);
    const stage = container.createDiv({ cls: "heptacard-split-stage" });
    this.stageEl = stage;
    stage.toggleClass("is-stream-collapsed", this.streamCollapsed);
    stage.style.setProperty("--heptacard-stream-width", `${this.streamWidthPercent}%`);
    const stream = stage.createDiv({ cls: "heptacard-stream-pane" });
    this.streamEl = stream;
    this.renderStreamPane(stream);
    const resizer = stage.createDiv({ cls: "heptacard-pane-resizer" });
    this.bindPaneResizer(resizer, stage);
    const gridPane = stage.createDiv({ cls: "heptacard-grid-pane" });
    this.gridEl = gridPane.createDiv({ cls: "heptacard-grid" });
    this.gridEl.addClass(`is-preview-${this.previewSize}`);
    this.applyPreviewScale(this.gridEl);
    this.renderCards(this.gridEl);
    this.bindMarquee(this.gridEl);
    const footer = container.createDiv({ cls: "heptacard-footer-count" });
    footer.createSpan({ text: `\u6570\u91CF  ${this.getVisibleCards().length}` });
  }
  renderTopbar(container) {
    const top = container.createDiv({ cls: "heptacard-topbar" });
    const toggle = top.createEl("button", {
      cls: "clickable-icon heptacard-collapse-toggle",
      attr: { "aria-label": this.streamCollapsed ? "\u5C55\u5F00\u7F16\u8F91\u6D41" : "\u6298\u53E0\u7F16\u8F91\u6D41" }
    });
    this.collapseToggleEl = toggle;
    (0, import_obsidian3.setIcon)(toggle, this.streamCollapsed ? "panel-left-open" : "panel-left-close");
    toggle.addEventListener("click", () => {
      this.streamCollapsed = !this.streamCollapsed;
      this.syncCollapsedState();
    });
    const searchWrap = top.createDiv({ cls: "heptacard-search-wrap" });
    (0, import_obsidian3.setIcon)(searchWrap.createSpan({ cls: "heptacard-search-icon" }), "search");
    const search = searchWrap.createEl("input", {
      cls: "heptacard-search",
      attr: { type: "search", placeholder: "\u67E5\u627E\u5361\u7247..." }
    });
    search.value = this.query;
    search.addEventListener("input", () => {
      this.query = search.value;
      this.render();
    });
    top.createDiv({ cls: "toolbar-divider" });
    const filters = top.createDiv({ cls: "heptacard-toolbar-group" });
    this.renderIconButton(filters, "layers", this.currentBoxLabel(), (event) => this.openBoxMenu(event));
    this.renderIconButton(filters, this.tagFilter ? "hash" : "filter", this.tagFilter ? `#${this.tagFilter}` : "\u6807\u7B7E\u7B5B\u9009", (event) => this.openTagMenu(event), !!this.tagFilter);
    this.renderIconButton(filters, "sliders-horizontal", `\u6392\u5E8F\uFF1A${this.sortLabel()}`, (event) => this.openSortMenu(event));
    this.renderIconButton(filters, this.previewSizeIcon(), this.previewSizeLabel(), (event) => this.openPreviewSizeMenu(event));
    top.createDiv({ cls: "toolbar-divider" });
    const actions = top.createDiv({ cls: "heptacard-toolbar-group" });
    const newCard = actions.createEl("button", { cls: "clickable-icon heptacard-ghost-icon", attr: { "aria-label": "\u65B0\u5EFA\u5361\u7247" } });
    (0, import_obsidian3.setIcon)(newCard, "plus");
    newCard.addEventListener("click", () => this.createCard());
    const imageToggle = actions.createEl("button", {
      cls: "clickable-icon heptacard-ghost-icon",
      attr: { "aria-label": "\u4EC5\u770B\u56FE\u7247\u5361\u7247" }
    });
    (0, import_obsidian3.setIcon)(imageToggle, "image");
    imageToggle.toggleClass("is-active", this.imageOnly);
    imageToggle.addEventListener("click", () => {
      this.imageOnly = !this.imageOnly;
      this.render();
    });
    const sortIcon = actions.createEl("button", { cls: "clickable-icon heptacard-ghost-icon", attr: { "aria-label": "\u6392\u5E8F" } });
    (0, import_obsidian3.setIcon)(sortIcon, "arrow-up-down");
    sortIcon.addEventListener("click", (event) => this.openSortMenu(event));
    const multiDelete = actions.createEl("button", { cls: "clickable-icon heptacard-ghost-icon", attr: { "aria-label": "\u6279\u91CF\u5220\u9664" } });
    (0, import_obsidian3.setIcon)(multiDelete, "trash-2");
    multiDelete.addEventListener("click", () => this.deleteSelected());
  }
  renderIconButton(container, icon, label, onClick, active = false) {
    const pill = container.createEl("button", {
      cls: "heptacard-filter-pill",
      attr: { "aria-label": label, title: label }
    });
    (0, import_obsidian3.setIcon)(pill.createSpan({ cls: "heptacard-pill-icon" }), icon);
    pill.toggleClass("is-active", active);
    pill.addEventListener("click", onClick);
    return pill;
  }
  renderBulkBar(container) {
    const bar = container.createDiv({ cls: "heptacard-bulk-bar" });
    bar.createSpan({ text: `${this.selectedCardIds.size} \u5F20\u5DF2\u9009\u62E9` });
    const move = bar.createEl("button", { cls: "clickable-icon", attr: { "aria-label": "\u79FB\u52A8" } });
    (0, import_obsidian3.setIcon)(move, "folder-symlink");
    move.addEventListener("click", () => this.moveSelected());
    const tag = bar.createEl("button", { cls: "clickable-icon", attr: { "aria-label": "\u52A0\u6807\u7B7E" } });
    (0, import_obsidian3.setIcon)(tag, "tag");
    tag.addEventListener("click", () => this.tagSelected());
    const del = bar.createEl("button", { cls: "clickable-icon mod-warning", attr: { "aria-label": "\u5220\u9664" } });
    (0, import_obsidian3.setIcon)(del, "trash-2");
    del.addEventListener("click", () => this.deleteSelected());
    const clear = bar.createEl("button", { cls: "clickable-icon", attr: { "aria-label": "\u53D6\u6D88\u9009\u62E9" } });
    (0, import_obsidian3.setIcon)(clear, "x");
    clear.addEventListener("click", () => {
      this.selectedCardIds.clear();
      this.render();
    });
  }
  renderStreamPane(container) {
    const cards = this.getVisibleCards();
    const stream = container.createDiv({ cls: "heptacard-stream-list" });
    if (!cards.length) {
      const empty = stream.createDiv({ cls: "heptacard-empty heptacard-stream-empty" });
      empty.createEl("h3", { text: "\u8FD8\u6CA1\u6709\u5361\u7247" });
      empty.createEl("p", { text: "\u70B9\u51FB\u9876\u90E8\u7684\u65B0\u5EFA\u5361\u7247\uFF0C\u5199\u4E0B\u7B2C\u4E00\u5F20\u5361\u7247\u3002" });
      return;
    }
    cards.forEach((card) => {
      const item = stream.createEl("article", { cls: "heptacard-stream-card" });
      item.dataset.cardId = card.id;
      item.toggleClass("is-highlighted", card.id === this.highlightedCardId);
      void this.renderStreamCard(item, card);
    });
  }
  async renderStreamCard(container, card) {
    var _a;
    const file = this.plugin.app.vault.getFileByPath(card.filePath);
    if (!file) {
      container.createDiv({ cls: "heptacard-muted", text: "\u5361\u7247\u6587\u4EF6\u4E0D\u5B58\u5728\u3002" });
      return;
    }
    const token = ((_a = this.renderTokens.get(card.id)) != null ? _a : 0) + 1;
    this.renderTokens.set(card.id, token);
    if (this.renderTokens.get(card.id) !== token)
      return;
    const header = container.createDiv({ cls: "heptacard-stream-card-header heptacard-stream-card-toolbar" });
    const meta = header.createDiv({ cls: "heptacard-stream-meta" });
    this.renderStreamMeta(meta, "map", card.boxName);
    this.renderStreamMeta(meta, "clock", new Date(card.updated).toLocaleDateString());
    card.tags.forEach((tag) => meta.createSpan({ cls: "heptacard-tag", text: `#${tag}` }));
    const actions = header.createDiv({ cls: "heptacard-stream-actions" });
    this.renderNativeModeButton(actions, card, "source", "code-2", "\u6E90\u7801\u6A21\u5F0F");
    this.renderNativeModeButton(actions, card, "live", "wrap-text", "\u5B9E\u65F6\u9884\u89C8");
    this.renderNativeModeButton(actions, card, "reading", "book-open", "\u9605\u8BFB\u89C6\u56FE");
    const box = actions.createEl("button", { cls: "clickable-icon heptacard-stream-action", attr: { "aria-label": "\u79FB\u52A8\u5230\u5361\u7247\u76D2" } });
    (0, import_obsidian3.setIcon)(box, "folder-symlink");
    box.addEventListener("click", (event) => {
      event.stopPropagation();
      this.openMoveCardMenu(event, card);
    });
    const del = actions.createEl("button", { cls: "clickable-icon heptacard-stream-action", attr: { "aria-label": "\u5220\u9664\u5F53\u524D\u5361\u7247" } });
    (0, import_obsidian3.setIcon)(del, "trash-2");
    del.addEventListener("click", async (event) => {
      event.stopPropagation();
      await this.plugin.storage.deleteCard(card);
      await this.plugin.refreshCards();
      this.render();
    });
    const open = actions.createEl("button", { cls: "clickable-icon heptacard-stream-action", attr: { "aria-label": "\u5728\u65B0\u6807\u7B7E\u9875\u6253\u5F00" } });
    (0, import_obsidian3.setIcon)(open, "external-link");
    open.addEventListener("click", (event) => {
      event.stopPropagation();
      void this.plugin.openCardInNewTab(card, this.nativeMode);
    });
    const copy = actions.createEl("button", { cls: "clickable-icon heptacard-stream-action", attr: { "aria-label": "\u590D\u5236\u5D4C\u5165" } });
    (0, import_obsidian3.setIcon)(copy, "copy");
    copy.addEventListener("click", async (event) => {
      event.stopPropagation();
      await navigator.clipboard.writeText(this.plugin.makeEmbed(card, ""));
      new import_obsidian3.Notice("\u5DF2\u590D\u5236\u5361\u7247\u5D4C\u5165");
    });
    const bodyHost = container.createDiv({ cls: "heptacard-stream-body is-native-active" });
    const host = bodyHost.createDiv({ cls: "heptacard-native-editor-host" });
    window.setTimeout(() => void this.mountNativeEditor(card.id, host), 0);
    const info = container.createDiv({ cls: "heptacard-stream-info" });
    await renderInfoPanel(this.plugin, info, card);
  }
  renderStreamMeta(container, icon, text) {
    const item = container.createSpan({ cls: "heptacard-stream-meta-item" });
    (0, import_obsidian3.setIcon)(item.createSpan(), icon);
    item.createSpan({ text });
  }
  renderNativeModeButton(container, card, mode, icon, label) {
    const button = container.createEl("button", {
      cls: "clickable-icon heptacard-stream-action heptacard-native-mode-button",
      attr: { "aria-label": label }
    });
    (0, import_obsidian3.setIcon)(button, icon);
    button.dataset.mode = mode;
    button.toggleClass("is-active", this.nativeMode === mode);
    button.addEventListener("click", (event) => {
      event.stopPropagation();
      this.nativeMode = mode;
      this.syncNativeModeButtons();
      void this.setNativeEditorMode(card.id, mode);
    });
    return button;
  }
  syncNativeModeButtons() {
    var _a;
    (_a = this.streamEl) == null ? void 0 : _a.querySelectorAll(".heptacard-native-mode-button").forEach((button) => {
      const buttonMode = button.dataset.mode;
      button.toggleClass("is-active", buttonMode === this.nativeMode);
    });
  }
  async mountNativeEditor(cardId, host, mode = this.nativeMode) {
    var _a;
    const card = this.plugin.cards.find((item) => item.id === cardId);
    if (!card)
      return;
    const file = this.plugin.app.vault.getFileByPath(card.filePath);
    if (!file) {
      host.setText("\u5361\u7247\u6587\u4EF6\u4E0D\u5B58\u5728\u3002");
      return;
    }
    const existing = this.nativeEditors.get(cardId);
    if ((existing == null ? void 0 : existing.filePath) === file.path) {
      if (existing.rootSplit.containerEl.parentElement !== host) {
        host.empty();
        host.appendChild(existing.rootSplit.containerEl);
      }
      if (existing.mode !== mode) {
        await this.setNativeEditorMode(cardId, mode);
      } else {
        this.styleNativeLeaf(existing.leaf);
        window.setTimeout(() => existing.leaf.onResize(), 40);
      }
      return;
    }
    this.unloadNativeEditor(cardId);
    host.empty();
    host.addClass("is-loading");
    try {
      const rootSplit = this.createEmbeddedRootSplit(host);
      const leaf = this.createEmbeddedLeaf(rootSplit);
      const editorRecord = { cardId, filePath: file.path, mode, host, leaf, rootSplit };
      this.nativeEditors.set(cardId, editorRecord);
      host.addEventListener("pointerdown", () => {
        this.plugin.app.workspace.setActiveLeaf(leaf, { focus: false });
      }, { capture: true });
      this.plugin.suppressAutoRefresh(500);
      await leaf.openFile(file, { active: false, state: this.plugin.getMarkdownOpenState(mode) });
      await ((_a = leaf.loadIfDeferred) == null ? void 0 : _a.call(leaf));
      host.removeClass("is-loading");
      this.styleNativeLeaf(leaf);
      this.attachAutoHeight(editorRecord);
      window.setTimeout(() => leaf.onResize(), 40);
      window.setTimeout(() => leaf.onResize(), 180);
    } catch (error) {
      this.unloadNativeEditor(cardId);
      host.removeClass("is-loading");
      host.createDiv({
        cls: "heptacard-muted",
        text: "\u539F\u751F\u7F16\u8F91\u5668\u52A0\u8F7D\u5931\u8D25\uFF0C\u5DF2\u56DE\u9000\u4E3A\u53EA\u8BFB\u9884\u89C8\u3002"
      });
      const body = await this.plugin.storage.getCardBody(file);
      await this.renderPreview(host, body, file.path, `fallback-${card.id}`);
      console.error("HeptaCard native editor failed", error);
      new import_obsidian3.Notice("\u539F\u751F\u5361\u7247\u7F16\u8F91\u5668\u52A0\u8F7D\u5931\u8D25\uFF0C\u8BF7\u67E5\u770B\u63A7\u5236\u53F0\u3002");
    }
  }
  createEmbeddedRootSplit(host) {
    const SplitCtor = import_obsidian3.WorkspaceSplit;
    const rootSplit = new SplitCtor(this.plugin.app.workspace, "vertical");
    rootSplit.getRoot = () => this.plugin.app.workspace.rootSplit;
    rootSplit.getContainer = () => this.plugin.app.workspace.rootSplit;
    rootSplit.containerEl.addClass("heptacard-native-workspace-split");
    host.appendChild(rootSplit.containerEl);
    return rootSplit;
  }
  createEmbeddedLeaf(rootSplit) {
    const workspace = this.plugin.app.workspace;
    const originalSetActiveLeaf = workspace.setActiveLeaf;
    try {
      workspace.setActiveLeaf = () => void 0;
      return this.plugin.app.workspace.createLeafInParent(rootSplit, 0);
    } finally {
      workspace.setActiveLeaf = originalSetActiveLeaf;
    }
  }
  async setNativeEditorMode(cardId, mode) {
    this.nativeMode = mode;
    const editor = this.nativeEditors.get(cardId);
    if (!editor)
      return;
    if (editor.mode === mode)
      return;
    const file = this.plugin.app.vault.getFileByPath(editor.filePath);
    if (!file)
      return;
    this.plugin.suppressAutoRefresh(500);
    await editor.leaf.openFile(file, { active: false, state: this.plugin.getMarkdownOpenState(mode) });
    editor.mode = mode;
    this.styleNativeLeaf(editor.leaf);
    this.attachAutoHeight(editor);
    window.setTimeout(() => editor.leaf.onResize(), 40);
  }
  styleNativeLeaf(leaf) {
    var _a, _b, _c;
    leaf.containerEl.addClass("heptacard-native-leaf");
    const view = leaf.view;
    if (view instanceof import_obsidian3.MarkdownView) {
      view.contentEl.addClass("heptacard-native-markdown-view");
      (_b = (_a = view.editMode) == null ? void 0 : _a.reinit) == null ? void 0 : _b.call(_a);
      (_c = view.editor) == null ? void 0 : _c.refresh();
    }
  }
  focusNativeEditor() {
    var _a, _b, _c;
    const leaf = (_c = (_a = this.nativeEditors.get(this.highlightedCardId)) == null ? void 0 : _a.leaf) != null ? _c : (_b = Array.from(this.nativeEditors.values())[0]) == null ? void 0 : _b.leaf;
    if (!leaf)
      return;
    this.plugin.app.workspace.setActiveLeaf(leaf, { focus: true });
    if (leaf.view instanceof import_obsidian3.MarkdownView && leaf.view.getMode() === "source") {
      window.setTimeout(() => leaf.view instanceof import_obsidian3.MarkdownView && leaf.view.editor.focus(), 20);
    }
  }
  attachAutoHeight(editor) {
    var _a, _b;
    (_a = editor.heightCleanup) == null ? void 0 : _a.call(editor);
    if (editor.heightFrame)
      window.cancelAnimationFrame(editor.heightFrame);
    editor.heightFrame = void 0;
    (_b = editor.resizeObserver) == null ? void 0 : _b.disconnect();
    const view = editor.leaf.view;
    if (!(view instanceof import_obsidian3.MarkdownView))
      return;
    const setPanelHeight = (el, height) => {
      el.style.setProperty("height", `${height}px`, "important");
      el.style.setProperty("min-height", `${height}px`, "important");
    };
    const getContentTargets = () => Array.from(view.contentEl.querySelectorAll(
      ".cm-content, .markdown-preview-section"
    ));
    const measureContentHeight = () => {
      const contentTargets = getContentTargets();
      if (!contentTargets.length)
        return view.contentEl.scrollHeight;
      return contentTargets.reduce((max, el) => {
        const children = Array.from(el.children).filter((child) => {
          if (!(child instanceof HTMLElement) || child.offsetHeight <= 0)
            return false;
          return !child.hasClass("cm-gap") && !child.hasClass("cm-activeLineGutter");
        });
        if (!children.length)
          return max;
        const top = el.getBoundingClientRect().top;
        const childBottom = children.reduce((bottom, child) => {
          const rect = child.getBoundingClientRect();
          return Math.max(bottom, rect.bottom - top);
        }, 0);
        return Math.max(max, childBottom);
      }, 0);
    };
    const applyHeight = () => {
      var _a2;
      const height = Math.ceil(Math.max(120, measureContentHeight() + 54));
      if (Math.abs(((_a2 = editor.lastHeight) != null ? _a2 : 0) - height) <= 2)
        return;
      editor.lastHeight = height;
      setPanelHeight(editor.host, height);
      setPanelHeight(editor.rootSplit.containerEl, height);
      editor.host.querySelectorAll(".workspace-split, .workspace-tabs, .workspace-leaf, .workspace-leaf-content, .view-content").forEach((el) => setPanelHeight(el, height));
      window.setTimeout(() => editor.leaf.onResize(), 20);
    };
    const scheduleHeight = () => {
      if (editor.heightFrame)
        return;
      editor.heightFrame = window.requestAnimationFrame(() => {
        editor.heightFrame = void 0;
        applyHeight();
      });
    };
    const observer = new ResizeObserver(() => scheduleHeight());
    const observeTargets = () => {
      const targets = getContentTargets();
      (targets.length ? targets : [view.contentEl]).forEach((target) => observer.observe(target));
    };
    observeTargets();
    const onInput = () => scheduleHeight();
    editor.host.addEventListener("input", onInput, true);
    editor.host.addEventListener("keyup", onInput, true);
    editor.host.addEventListener("load", onInput, true);
    editor.resizeObserver = observer;
    editor.heightCleanup = () => {
      editor.host.removeEventListener("input", onInput, true);
      editor.host.removeEventListener("keyup", onInput, true);
      editor.host.removeEventListener("load", onInput, true);
      if (editor.heightFrame)
        window.cancelAnimationFrame(editor.heightFrame);
      editor.heightFrame = void 0;
    };
    window.setTimeout(scheduleHeight, 40);
    window.setTimeout(scheduleHeight, 180);
    window.setTimeout(scheduleHeight, 600);
  }
  unloadNativeEditor(cardId) {
    var _a, _b;
    const editor = this.nativeEditors.get(cardId);
    if (!editor)
      return;
    this.nativeEditors.delete(cardId);
    (_a = editor.heightCleanup) == null ? void 0 : _a.call(editor);
    (_b = editor.resizeObserver) == null ? void 0 : _b.disconnect();
    try {
      editor.leaf.detach();
    } catch (error) {
      console.error("HeptaCard native editor detach failed", error);
    }
    editor.rootSplit.containerEl.detach();
  }
  unloadNativeEditors() {
    Array.from(this.nativeEditors.keys()).forEach((cardId) => this.unloadNativeEditor(cardId));
  }
  previewSizeIcon() {
    switch (this.previewSize) {
      case "large":
        return "maximize-2";
      case "small":
        return "minimize-2";
      case "medium":
      default:
        return "panel-top";
    }
  }
  renderCards(container) {
    const cards = this.getVisibleCards();
    if (!cards.length) {
      const empty = container.createDiv({ cls: "heptacard-empty" });
      empty.createEl("h3", { text: "\u8FD8\u6CA1\u6709\u5361\u7247" });
      empty.createEl("p", { text: "\u70B9\u51FB\u9876\u90E8\u7684\u65B0\u5EFA\u5361\u7247\uFF0C\u5199\u4E0B\u7B2C\u4E00\u5F20\u5361\u7247\u3002" });
      return;
    }
    const fragment = document.createDocumentFragment();
    cards.forEach((card) => {
      const item = document.createElement("article");
      item.addClass("heptacard-board-card");
      item.toggleClass("is-selected", this.selectedCardIds.has(card.id));
      item.toggleClass("is-revealed", card.id === this.highlightedCardId);
      item.dataset.cardId = card.id;
      item.draggable = true;
      if (card.color)
        item.style.setProperty("--heptacard-accent", card.color);
      this.renderCardShell(item, card);
      fragment.appendChild(item);
    });
    container.appendChild(fragment);
  }
  renderCardShell(cardEl, card) {
    var _a;
    const openButton = cardEl.createEl("button", {
      cls: "clickable-icon heptacard-card-open",
      attr: { "aria-label": "\u5728\u5DE6\u4FA7\u5B9A\u4F4D" }
    });
    (0, import_obsidian3.setIcon)(openButton, "locate-fixed");
    openButton.addEventListener("click", (event) => {
      event.stopPropagation();
      void this.revealCard(card.id);
    });
    cardEl.createDiv({ cls: "heptacard-board-card-title", text: card.title });
    const body = cardEl.createDiv({ cls: "heptacard-board-card-body markdown-rendered" });
    const cached = (_a = this.plugin.cardBodyCache.get(card.id)) != null ? _a : "";
    cardEl.toggleClass("has-image-preview", this.markdownHasImage(cached));
    void this.renderPreview(body, cached, card.filePath, card.id);
    const footer = cardEl.createDiv({ cls: "heptacard-board-card-footer" });
    const tagRow = footer.createDiv({ cls: "heptacard-card-tags" });
    card.tags.slice(0, 3).forEach((tag) => tagRow.createSpan({ cls: "heptacard-tag", text: `#${tag}` }));
    const meta = footer.createDiv({ cls: "heptacard-card-mini-meta" });
    (0, import_obsidian3.setIcon)(meta.createSpan(), "map");
    meta.createSpan({ text: card.boxName });
    cardEl.addEventListener("click", (event) => {
      if (event.metaKey || event.ctrlKey) {
        this.toggleSelected(card.id);
        return;
      }
      if (this.selectedCardIds.size > 0) {
        this.toggleSelected(card.id);
        return;
      }
      void this.revealCard(card.id);
    });
    cardEl.addEventListener("dragstart", (event) => {
      var _a2, _b;
      (_a2 = event.dataTransfer) == null ? void 0 : _a2.setData("text/plain", this.plugin.makeEmbed(card, ""));
      (_b = event.dataTransfer) == null ? void 0 : _b.setData("text/markdown", this.plugin.makeEmbed(card, ""));
      cardEl.addClass("is-dragging");
    });
    cardEl.addEventListener("dragend", () => cardEl.removeClass("is-dragging"));
    cardEl.addEventListener("contextmenu", (event) => {
      event.preventDefault();
      this.openCardMenu(event, card);
    });
  }
  async renderPreview(container, markdown, sourcePath, cardId) {
    container.empty();
    const component = this.replacePreviewComponent(cardId);
    const preview = markdown.trim();
    if (preview)
      await import_obsidian3.MarkdownRenderer.render(this.app, preview, container, sourcePath, component);
  }
  markdownHasImage(markdown) {
    return /!\[\[[^\]]+\]\]|!\[[^\]]*]\([^)]+\)/.test(markdown);
  }
  syncCollapsedState() {
    var _a;
    (_a = this.stageEl) == null ? void 0 : _a.toggleClass("is-stream-collapsed", this.streamCollapsed);
    if (this.collapseToggleEl) {
      this.collapseToggleEl.setAttribute("aria-label", this.streamCollapsed ? "\u5C55\u5F00\u7F16\u8F91\u6D41" : "\u6298\u53E0\u7F16\u8F91\u6D41");
      this.collapseToggleEl.empty();
      (0, import_obsidian3.setIcon)(this.collapseToggleEl, this.streamCollapsed ? "panel-left-open" : "panel-left-close");
    }
    window.setTimeout(() => {
      this.nativeEditors.forEach((editor) => {
        editor.leaf.onResize();
        this.attachAutoHeight(editor);
      });
    }, 40);
  }
  openCardMenu(event, card) {
    const menu = new import_obsidian3.Menu();
    menu.addItem((item) => item.setTitle("\u5728\u65B0\u6807\u7B7E\u9875\u6253\u5F00").setIcon("external-link").onClick(() => this.plugin.openCardInNewTab(card)));
    menu.addItem((item) => item.setTitle("\u5728\u5DE5\u4F5C\u53F0\u5B9A\u4F4D").setIcon("locate-fixed").onClick(() => this.revealCard(card.id)));
    menu.addItem((item) => item.setTitle("\u590D\u5236\u5D4C\u5165").setIcon("copy").onClick(async () => {
      await navigator.clipboard.writeText(this.plugin.makeEmbed(card, ""));
      new import_obsidian3.Notice("\u5DF2\u590D\u5236\u5361\u7247\u5D4C\u5165");
    }));
    menu.addItem((item) => item.setTitle("\u5220\u9664").setIcon("trash").onClick(async () => {
      await this.plugin.storage.deleteCard(card);
      await this.plugin.refreshCards();
      this.render();
    }));
    menu.showAtMouseEvent(event);
  }
  openMoveCardMenu(event, card) {
    const menu = new import_obsidian3.Menu();
    this.plugin.settings.boxes.forEach((box) => {
      menu.addItem((item) => item.setTitle(box.name).setIcon(card.boxId === box.id ? "check" : "folder").onClick(async () => {
        var _a;
        const moved = await this.plugin.storage.moveCardToBox(card, box);
        await this.plugin.refreshCards();
        this.currentBoxId = box.id;
        this.highlightedCardId = (_a = moved == null ? void 0 : moved.id) != null ? _a : card.id;
        this.render();
        if (moved)
          window.setTimeout(() => void this.revealCard(moved.id), 50);
      }));
    });
    menu.addSeparator();
    menu.addItem((item) => item.setTitle("\u65B0\u5EFA\u5361\u7247\u76D2").setIcon("folder-plus").onClick(() => this.createBox()));
    menu.showAtMouseEvent(event);
  }
  openBoxMenu(event) {
    const menu = new import_obsidian3.Menu();
    menu.addItem((item) => item.setTitle("\u5168\u90E8\u5361\u7247").setIcon("layout-grid").onClick(() => {
      this.currentBoxId = "all";
      this.render();
    }));
    this.plugin.settings.boxes.forEach((box) => {
      menu.addItem((item) => item.setTitle(box.name).setIcon("map").onClick(() => {
        this.currentBoxId = box.id;
        this.render();
      }));
    });
    menu.addSeparator();
    menu.addItem((item) => item.setTitle("\u65B0\u5EFA\u5361\u7247\u76D2").setIcon("folder-plus").onClick(() => this.createBox()));
    menu.showAtMouseEvent(event);
  }
  openSortMenu(event) {
    const options = [
      ["created-desc", "\u521B\u5EFA\u65F6\u95F4\uFF1A\u65B0\u5230\u65E7"],
      ["created-asc", "\u521B\u5EFA\u65F6\u95F4\uFF1A\u65E7\u5230\u65B0"],
      ["updated-desc", "\u6700\u8FD1\u66F4\u65B0"],
      ["title-asc", "\u6807\u9898 A-Z"]
    ];
    const menu = new import_obsidian3.Menu();
    options.forEach(([value, label]) => {
      menu.addItem((item) => item.setTitle(label).setIcon(this.plugin.settings.sortMode === value ? "check" : "arrow-up-down").onClick(async () => {
        this.plugin.settings.sortMode = value;
        await this.plugin.saveSettings();
        this.render();
      }));
    });
    menu.showAtMouseEvent(event);
  }
  openTagMenu(event) {
    const menu = new import_obsidian3.Menu();
    const tags = this.getAvailableTags();
    menu.addItem((item) => item.setTitle("\u5168\u90E8\u6807\u7B7E").setIcon(this.tagFilter ? "circle" : "check").onClick(() => {
      this.tagFilter = "";
      this.render();
    }));
    if (tags.length)
      menu.addSeparator();
    tags.forEach((tag) => {
      menu.addItem((item) => item.setTitle(`#${tag}`).setIcon(this.tagFilter === tag ? "check" : "hash").onClick(() => {
        this.tagFilter = tag;
        this.render();
      }));
    });
    if (!tags.length) {
      menu.addItem((item) => item.setTitle("\u6682\u65E0\u6807\u7B7E").setIcon("hash").setDisabled(true));
    }
    menu.showAtMouseEvent(event);
  }
  openPreviewSizeMenu(event) {
    const options = [
      ["large", "\u5927\u89C6\u56FE", "maximize-2"],
      ["medium", "\u4E2D\u89C6\u56FE", "panel-top"],
      ["small", "\u5C0F\u89C6\u56FE", "minimize-2"]
    ];
    const menu = new import_obsidian3.Menu();
    options.forEach(([value, label, icon]) => {
      menu.addItem((item) => item.setTitle(label).setIcon(this.previewSize === value ? "check" : icon).onClick(() => {
        var _a, _b;
        this.previewSize = value;
        (_a = this.gridEl) == null ? void 0 : _a.removeClass("is-preview-small", "is-preview-medium", "is-preview-large");
        (_b = this.gridEl) == null ? void 0 : _b.addClass(`is-preview-${value}`);
        if (this.gridEl)
          this.applyPreviewScale(this.gridEl);
      }));
    });
    menu.showAtMouseEvent(event);
  }
  getVisibleCards() {
    let cards = [...this.plugin.cards];
    if (this.currentBoxId !== "all")
      cards = cards.filter((card) => card.boxId === this.currentBoxId);
    if (this.query.trim())
      cards = this.plugin.searchCards(this.query).filter((card) => cards.some((item) => item.id === card.id));
    if (this.tagFilter.trim())
      cards = cards.filter((card) => card.tags.some((tag) => tag.toLowerCase() === this.tagFilter.toLowerCase()));
    if (this.imageOnly) {
      cards = cards.filter((card) => {
        var _a;
        return (_a = this.plugin.cardBodyCache.get(card.id)) == null ? void 0 : _a.match(/!\[[^\]]*\]\([^)]+\)|!\[\[[^\]]+\]\]/);
      });
    }
    return this.plugin.sortCards(cards);
  }
  getAvailableTags() {
    const cardTags = (this.currentBoxId === "all" ? this.plugin.cards : this.plugin.cards.filter((card) => card.boxId === this.currentBoxId)).flatMap((card) => card.tags);
    const vaultTags = this.plugin.app.vault.getMarkdownFiles().flatMap((file) => {
      var _a, _b;
      const cache = this.plugin.app.metadataCache.getFileCache(file);
      return (_b = (_a = cache == null ? void 0 : cache.tags) == null ? void 0 : _a.map((tag) => tag.tag.replace(/^#/, ""))) != null ? _b : [];
    });
    return Array.from(/* @__PURE__ */ new Set([...cardTags, ...vaultTags])).filter(Boolean).sort((a, b) => a.localeCompare(b, "zh-Hans-CN"));
  }
  bindMarquee(grid) {
    grid.addEventListener("pointerdown", (event) => {
      if (!event.shiftKey || event.button !== 0)
        return;
      this.dragStart = { x: event.clientX, y: event.clientY };
      this.selectionBox = grid.createDiv({ cls: "heptacard-selection-box" });
      grid.setPointerCapture(event.pointerId);
    });
    grid.addEventListener("pointermove", (event) => {
      if (!this.dragStart || !this.selectionBox)
        return;
      const rect = grid.getBoundingClientRect();
      const x1 = Math.min(this.dragStart.x, event.clientX) - rect.left + grid.scrollLeft;
      const y1 = Math.min(this.dragStart.y, event.clientY) - rect.top + grid.scrollTop;
      const x2 = Math.max(this.dragStart.x, event.clientX) - rect.left + grid.scrollLeft;
      const y2 = Math.max(this.dragStart.y, event.clientY) - rect.top + grid.scrollTop;
      this.selectionBox.style.left = `${x1}px`;
      this.selectionBox.style.top = `${y1}px`;
      this.selectionBox.style.width = `${x2 - x1}px`;
      this.selectionBox.style.height = `${y2 - y1}px`;
    });
    grid.addEventListener("pointerup", (event) => {
      if (!this.dragStart || !this.selectionBox)
        return;
      const boxRect = this.selectionBox.getBoundingClientRect();
      grid.querySelectorAll(".heptacard-board-card").forEach((cardEl) => {
        const rect = cardEl.getBoundingClientRect();
        const overlaps = !(rect.right < boxRect.left || rect.left > boxRect.right || rect.bottom < boxRect.top || rect.top > boxRect.bottom);
        if (overlaps && cardEl.dataset.cardId)
          this.selectedCardIds.add(cardEl.dataset.cardId);
      });
      this.selectionBox.remove();
      this.selectionBox = void 0;
      this.dragStart = void 0;
      grid.releasePointerCapture(event.pointerId);
      this.render();
    });
  }
  bindPaneResizer(handle, stage) {
    let resizing = false;
    const updateWidth = (clientX) => {
      const rect = stage.getBoundingClientRect();
      const raw = (clientX - rect.left) / rect.width * 100;
      const next = Math.min(72, Math.max(28, raw));
      this.streamWidthPercent = next;
      stage.style.setProperty("--heptacard-stream-width", `${next}%`);
    };
    handle.addEventListener("pointerdown", (event) => {
      if (this.streamCollapsed || event.button !== 0)
        return;
      resizing = true;
      handle.setPointerCapture(event.pointerId);
      stage.addClass("is-resizing");
      updateWidth(event.clientX);
    });
    handle.addEventListener("pointermove", (event) => {
      if (!resizing)
        return;
      updateWidth(event.clientX);
    });
    handle.addEventListener("pointerup", (event) => {
      if (!resizing)
        return;
      resizing = false;
      handle.releasePointerCapture(event.pointerId);
      stage.removeClass("is-resizing");
    });
    handle.addEventListener("pointercancel", (event) => {
      resizing = false;
      if (handle.hasPointerCapture(event.pointerId))
        handle.releasePointerCapture(event.pointerId);
      stage.removeClass("is-resizing");
    });
  }
  async createBox() {
    new BoxModal(this.app, {
      title: "\u65B0\u5EFA\u5361\u7247\u76D2",
      submitText: "\u521B\u5EFA",
      onSubmit: async (name, description) => {
        const box = this.plugin.storage.createBoxRecord(name, description);
        this.plugin.settings.boxes.push(box);
        await this.plugin.storage.ensureBoxFolder(box);
        if (!this.plugin.settings.defaultBoxId)
          this.plugin.settings.defaultBoxId = box.id;
        await this.plugin.saveSettings();
        this.currentBoxId = box.id;
        await this.plugin.refreshCards();
        this.render();
      }
    }).open();
  }
  async createCard() {
    var _a;
    const box = (_a = this.plugin.settings.boxes.find((item) => item.id === this.currentBoxId)) != null ? _a : this.plugin.getDefaultBox();
    if (!box) {
      new import_obsidian3.Notice("\u8BF7\u5148\u521B\u5EFA\u4E00\u4E2A\u5361\u7247\u76D2");
      return;
    }
    const title = this.nextUntitledCardTitle();
    const card = await this.plugin.storage.createCard(box, title, `# ${title}

`);
    if (!card)
      return;
    await this.plugin.refreshCards();
    this.currentBoxId = box.id;
    this.highlightedCardId = card.id;
    this.streamCollapsed = false;
    this.render();
    window.setTimeout(() => void this.revealCard(card.id), 80);
  }
  nextUntitledCardTitle() {
    const base = "\u672A\u547D\u540D\u5361\u7247";
    const titles = new Set(this.plugin.cards.map((card) => card.title));
    if (!titles.has(base))
      return base;
    let index = 2;
    while (titles.has(`${base} ${index}`))
      index += 1;
    return `${base} ${index}`;
  }
  async renameBox(box) {
    new BoxModal(this.app, {
      title: "\u91CD\u547D\u540D\u5361\u7247\u76D2",
      submitText: "\u4FDD\u5B58",
      name: box.name,
      description: box.description,
      onSubmit: async (name, description) => {
        box.name = name;
        box.description = description;
        box.updated = Date.now();
        await this.plugin.saveSettings();
        this.render();
      }
    }).open();
  }
  async moveSelected() {
    new SelectBoxModal(this.app, this.plugin.settings.boxes, async (box) => {
      const cards = this.plugin.cards.filter((card) => this.selectedCardIds.has(card.id));
      for (const card of cards)
        await this.plugin.storage.moveCardToBox(card, box);
      this.selectedCardIds.clear();
      await this.plugin.refreshCards();
      this.render();
    }).open();
  }
  async tagSelected() {
    new TextInputModal(this.app, {
      title: "\u6279\u91CF\u6DFB\u52A0\u6807\u7B7E",
      placeholder: "\u8F93\u5165\u6807\u7B7E\uFF0C\u4E0D\u9700\u8981 #",
      submitText: "\u6DFB\u52A0",
      onSubmit: async (value) => {
        const normalized = value.trim().replace(/^#/, "");
        if (!normalized)
          return;
        const cards = this.plugin.cards.filter((card) => this.selectedCardIds.has(card.id));
        for (const card of cards) {
          const file = this.plugin.app.vault.getFileByPath(card.filePath);
          if (!file)
            continue;
          const body = await this.plugin.storage.getCardBody(file);
          const tags = Array.from(/* @__PURE__ */ new Set([...card.tags, normalized]));
          await this.plugin.storage.writeCard({ ...card, tags }, body);
        }
        this.selectedCardIds.clear();
        await this.plugin.refreshCards();
        this.render();
      }
    }).open();
  }
  async deleteSelected() {
    const cards = this.plugin.cards.filter((card) => this.selectedCardIds.has(card.id));
    if (!cards.length) {
      new import_obsidian3.Notice("\u8BF7\u5148\u9009\u62E9\u8981\u5220\u9664\u7684\u5361\u7247");
      return;
    }
    for (const card of cards)
      await this.plugin.storage.deleteCard(card);
    this.selectedCardIds.clear();
    await this.plugin.refreshCards();
    this.render();
    new import_obsidian3.Notice("\u5DF2\u5220\u9664\u6240\u9009\u5361\u7247");
  }
  toggleSelected(id) {
    if (this.selectedCardIds.has(id))
      this.selectedCardIds.delete(id);
    else
      this.selectedCardIds.add(id);
    this.render();
  }
  currentBoxLabel() {
    var _a, _b;
    if (this.currentBoxId === "all")
      return "\u5168\u90E8\u5361\u7247";
    return (_b = (_a = this.plugin.settings.boxes.find((box) => box.id === this.currentBoxId)) == null ? void 0 : _a.name) != null ? _b : "\u5168\u90E8\u5361\u7247";
  }
  sortLabel() {
    switch (this.plugin.settings.sortMode) {
      case "created-asc":
        return "\u65E7\u5230\u65B0";
      case "updated-desc":
        return "\u6700\u8FD1\u66F4\u65B0";
      case "title-asc":
        return "A-Z";
      case "created-desc":
      default:
        return "\u65B0\u5230\u65E7";
    }
  }
  previewSizeLabel() {
    switch (this.previewSize) {
      case "large":
        return "\u5927\u89C6\u56FE";
      case "small":
        return "\u5C0F\u89C6\u56FE";
      case "medium":
      default:
        return "\u4E2D\u89C6\u56FE";
    }
  }
  applyPreviewScale(grid) {
    const presets = {
      small: { min: 156, height: 144, image: 58, body: 11 },
      medium: { min: 182, height: 174, image: 78, body: 12 },
      large: { min: 260, height: 264, image: 136, body: 14 }
    };
    const scaleMap = {
      small: this.plugin.settings.previewSmallScale / 100,
      medium: this.plugin.settings.previewMediumScale / 100,
      large: this.plugin.settings.previewLargeScale / 100
    };
    const preset = presets[this.previewSize];
    const scale = scaleMap[this.previewSize];
    grid.style.setProperty("--heptacard-preview-min", `${Math.round(preset.min * scale)}px`);
    grid.style.setProperty("--heptacard-preview-height", `${Math.round(preset.height * scale)}px`);
    grid.style.setProperty("--heptacard-preview-image-height", `${Math.round(preset.image * scale)}px`);
    grid.style.setProperty("--heptacard-preview-title-size", `${this.plugin.settings.previewTitleSize}px`);
    grid.style.setProperty("--heptacard-preview-body-size", `${preset.body}px`);
  }
  trimPreviewMarkdown(markdown) {
    const clean = markdown.replace(/^---[\s\S]*?---/, "").trim();
    if (!clean)
      return "";
    return clean.split(/\n{2,}/).slice(0, 2).join("\n\n").slice(0, 900);
  }
  unloadPreviewComponents() {
    this.previewComponents.forEach((component) => {
      this.removeChild(component);
    });
    this.previewComponents = [];
    this.previewComponentByCard.clear();
    this.lastRenderedPreview.clear();
    this.previewSyncTimers.forEach((timer) => window.clearTimeout(timer));
    this.previewSyncTimers.clear();
  }
  updateGridCard(cardId) {
    var _a, _b;
    const card = this.plugin.cards.find((item) => item.id === cardId);
    const gridCard = (_a = this.gridEl) == null ? void 0 : _a.querySelector(`.heptacard-board-card[data-card-id="${cardId}"]`);
    if (!card || !gridCard)
      return;
    const title = gridCard.querySelector(".heptacard-board-card-title");
    if (title)
      title.setText(card.title);
    this.updateCardPreview(cardId, (_b = this.plugin.cardBodyCache.get(cardId)) != null ? _b : "");
  }
  updateCardPreview(cardId, markdown) {
    var _a, _b, _c;
    const preview = (_a = this.gridEl) == null ? void 0 : _a.querySelector(`.heptacard-board-card[data-card-id="${cardId}"] .heptacard-board-card-body`);
    if (!preview)
      return;
    if (this.lastRenderedPreview.get(cardId) === markdown)
      return;
    this.lastRenderedPreview.set(cardId, markdown);
    preview.empty();
    const component = this.replacePreviewComponent(cardId);
    const previewMarkdown = markdown.trim();
    if (previewMarkdown)
      void import_obsidian3.MarkdownRenderer.render(this.app, previewMarkdown, preview, (_c = (_b = this.plugin.cards.find((card) => card.id === cardId)) == null ? void 0 : _b.filePath) != null ? _c : "", component);
  }
  async refreshGridOnly() {
    if (!this.gridEl)
      return;
    this.applyPreviewScale(this.gridEl);
    const cards = this.getVisibleCards();
    const current = Array.from(this.gridEl.querySelectorAll(".heptacard-board-card")).map((el) => {
      var _a;
      return (_a = el.dataset.cardId) != null ? _a : "";
    });
    const sameOrder = current.length === cards.length && current.every((id, index) => {
      var _a;
      return id === ((_a = cards[index]) == null ? void 0 : _a.id);
    });
    if (!sameOrder) {
      const scrollTop = this.gridEl.scrollTop;
      const scrollLeft = this.gridEl.scrollLeft;
      this.gridEl.empty();
      this.renderCards(this.gridEl);
      this.gridEl.scrollTop = scrollTop;
      this.gridEl.scrollLeft = scrollLeft;
      return;
    }
    cards.forEach((card) => this.updateGridCard(card.id));
  }
  replacePreviewComponent(cardId) {
    const existing = this.previewComponentByCard.get(cardId);
    if (existing) {
      this.removeChild(existing);
      this.previewComponents = this.previewComponents.filter((component2) => component2 !== existing);
    }
    const component = this.addChild(new import_obsidian3.Component());
    component.load();
    this.previewComponentByCard.set(cardId, component);
    this.previewComponents.push(component);
    return component;
  }
};
var TextInputModal = class extends import_obsidian3.Modal {
  constructor(app, config) {
    super(app);
    this.config = config;
  }
  onOpen() {
    this.setTitle(this.config.title);
    const setting = new import_obsidian3.Setting(this.contentEl).addText((text) => {
      var _a, _b;
      this.input = text;
      text.setPlaceholder((_a = this.config.placeholder) != null ? _a : "").setValue((_b = this.config.value) != null ? _b : "");
    });
    setting.settingEl.addClass("heptacard-modal-field");
    this.renderButtons();
    window.setTimeout(() => {
      var _a;
      return (_a = this.input) == null ? void 0 : _a.inputEl.focus();
    }, 50);
  }
  renderButtons() {
    const buttons = this.contentEl.createDiv({ cls: "heptacard-modal-actions" });
    new import_obsidian3.ButtonComponent(buttons).setButtonText("\u53D6\u6D88").onClick(() => this.close());
    new import_obsidian3.ButtonComponent(buttons).setButtonText(this.config.submitText).setCta().onClick(async () => {
      await this.config.onSubmit(this.input.getValue());
      this.close();
    });
  }
};
var BoxModal = class extends import_obsidian3.Modal {
  constructor(app, config) {
    super(app);
    this.config = config;
  }
  onOpen() {
    this.setTitle(this.config.title);
    new import_obsidian3.Setting(this.contentEl).setName("\u540D\u79F0").addText((text) => {
      var _a;
      this.nameInput = text;
      text.setPlaceholder("\u4F8B\u5982\uFF1A\u5199\u4F5C\u7075\u611F").setValue((_a = this.config.name) != null ? _a : "");
    });
    new import_obsidian3.Setting(this.contentEl).setName("\u63CF\u8FF0").addText((text) => {
      var _a;
      this.descInput = text;
      text.setPlaceholder("\u53EF\u9009").setValue((_a = this.config.description) != null ? _a : "");
    });
    const buttons = this.contentEl.createDiv({ cls: "heptacard-modal-actions" });
    new import_obsidian3.ButtonComponent(buttons).setButtonText("\u53D6\u6D88").onClick(() => this.close());
    new import_obsidian3.ButtonComponent(buttons).setButtonText(this.config.submitText).setCta().onClick(async () => {
      const name = this.nameInput.getValue().trim();
      if (!name) {
        new import_obsidian3.Notice("\u8BF7\u8F93\u5165\u540D\u79F0");
        return;
      }
      await this.config.onSubmit(name, this.descInput.getValue().trim());
      this.close();
    });
    window.setTimeout(() => {
      var _a;
      return (_a = this.nameInput) == null ? void 0 : _a.inputEl.focus();
    }, 50);
  }
};
var SelectBoxModal = class extends import_obsidian3.Modal {
  constructor(app, boxes, onSubmit) {
    var _a, _b;
    super(app);
    this.selectedId = "";
    this.boxes = boxes;
    this.onSubmit = onSubmit;
    this.selectedId = (_b = (_a = boxes[0]) == null ? void 0 : _a.id) != null ? _b : "";
  }
  onOpen() {
    this.setTitle("\u79FB\u52A8\u5230\u5361\u7247\u76D2");
    new import_obsidian3.Setting(this.contentEl).setName("\u5361\u7247\u76D2").addDropdown((dropdown) => {
      this.boxes.forEach((box) => dropdown.addOption(box.id, box.name));
      dropdown.setValue(this.selectedId);
      dropdown.onChange((value) => {
        this.selectedId = value;
      });
    });
    const buttons = this.contentEl.createDiv({ cls: "heptacard-modal-actions" });
    new import_obsidian3.ButtonComponent(buttons).setButtonText("\u53D6\u6D88").onClick(() => this.close());
    new import_obsidian3.ButtonComponent(buttons).setButtonText("\u79FB\u52A8").setCta().onClick(async () => {
      const box = this.boxes.find((item) => item.id === this.selectedId);
      if (!box)
        return;
      await this.onSubmit(box);
      this.close();
    });
  }
};

// main.ts
var HeptaCardPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.cards = [];
    this.cardBodyCache = /* @__PURE__ */ new Map();
    this.suppressAutoRefreshUntil = 0;
  }
  async onload() {
    await this.loadSettings();
    this.storage = new HeptaCardStorage(this.app, this.settings);
    this.embedRenderer = new HeptaCardEmbedRenderer(this);
    await this.migrateSettings();
    await this.storage.ensureFolders();
    await this.refreshCards();
    await this.ensureDefaultBox();
    this.registerView(VIEW_TYPE_HEPTACARD, (leaf) => new HeptaCardWorkbenchView(leaf, this));
    this.registerMarkdownPostProcessor(this.postProcessMarkdown.bind(this), 10);
    this.registerMarkdownCodeBlockProcessor(CARD_BLOCK_LANGUAGE, (source, el, ctx) => renderCardBlock(this, source, el, ctx));
    this.registerMarkdownCodeBlockProcessor("heptacard", (source, el, ctx) => renderCardBlock(this, source, el, ctx));
    this.registerEditorSuggest(new SlashCardSuggest(this.app, this));
    this.addSettingTab(new HeptaCardSettingTab(this.app, this));
    this.addRibbonIcon("layout-grid", "\u6253\u5F00\u5361\u7247\u76D2", () => this.openWorkbench());
    this.addCommand({
      id: "cardbox-open-workbench",
      name: "\u6253\u5F00\u5361\u7247\u76D2\u5DE5\u4F5C\u53F0",
      callback: () => this.openWorkbench()
    });
    this.addCommand({
      id: "cardbox-create-card",
      name: "\u65B0\u5EFA\u5361\u7247",
      callback: () => this.promptCreateCard()
    });
    this.addCommand({
      id: "cardbox-insert-card",
      name: "\u63D2\u5165\u5361\u7247",
      editorCallback: (editor, view) => {
        const modal = new CardInsertModal(this.app, this, (card) => {
          var _a, _b;
          const text = this.makeEmbed(card, (_b = (_a = view.file) == null ? void 0 : _a.path) != null ? _b : "");
          editor.replaceSelection(text);
        });
        modal.open();
      }
    });
    this.setupFolderHiding();
    this.registerCardRefreshHooks();
    this.app.workspace.onLayoutReady(() => {
      this.refreshViews();
      this.applyHiddenFolders();
    });
  }
  onunload() {
  }
  async loadSettings() {
    var _a, _b, _c;
    const data = (_a = await this.loadData()) != null ? _a : {};
    delete data.cards;
    delete data.references;
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
    if (!this.settings.defaultBoxId) {
      this.settings.defaultBoxId = (_c = (_b = this.settings.boxes[0]) == null ? void 0 : _b.id) != null ? _c : "";
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async migrateSettings() {
    var _a, _b;
    const data = await this.loadData();
    if (!data) {
      await this.saveSettings();
      return;
    }
    if (Array.isArray(data.cards) || Array.isArray(data.references)) {
      delete this.settings.cards;
      delete this.settings.references;
      if (!this.settings.defaultBoxId)
        this.settings.defaultBoxId = (_b = (_a = this.settings.boxes[0]) == null ? void 0 : _a.id) != null ? _b : "";
      await this.saveSettings();
      return;
    }
    let changed = false;
    if (this.settings.cardsFolder === "_HeptaCards") {
      this.settings.cardsFolder = "_CardBox/Cards";
      changed = true;
    }
    if (this.settings.boxesFolder === "_HeptaCardBoxes") {
      this.settings.boxesFolder = "_CardBox/Boxes";
      changed = true;
    }
    if (this.settings.hiddenFolderPaths.includes("_HeptaCards") || this.settings.hiddenFolderPaths.includes("_HeptaCardBoxes")) {
      for (const path of ["_CardBox", "_CardBox/Cards", "_CardBox/Boxes"]) {
        if (!this.settings.hiddenFolderPaths.includes(path)) {
          this.settings.hiddenFolderPaths.push(path);
          changed = true;
        }
      }
    }
    for (const key of ["previewSmallScale", "previewMediumScale", "previewLargeScale"]) {
      if (!Number.isFinite(this.settings[key])) {
        this.settings[key] = DEFAULT_SETTINGS[key];
        changed = true;
      }
    }
    if (!Number.isFinite(this.settings.previewTitleSize)) {
      this.settings.previewTitleSize = DEFAULT_SETTINGS.previewTitleSize;
      changed = true;
    }
    if (changed) {
      await this.saveSettings();
    }
  }
  async ensureDefaultBox() {
    if (this.settings.boxes.length)
      return;
    const box = this.storage.createBoxRecord("\u6536\u96C6\u7BB1", "\u9ED8\u8BA4\u5361\u7247\u76D2");
    this.settings.boxes.push(box);
    this.settings.defaultBoxId = box.id;
    await this.storage.ensureBoxFolder(box);
    await this.saveSettings();
  }
  getDefaultBox() {
    var _a;
    return (_a = this.settings.boxes.find((box) => box.id === this.settings.defaultBoxId)) != null ? _a : this.settings.boxes[0];
  }
  async refreshCards() {
    const all = await this.storage.readAllCards();
    this.cards = all.map((card) => {
      var _a;
      const box = this.settings.boxes.find((item) => item.id === card.boxId);
      return {
        ...card,
        boxName: (_a = box == null ? void 0 : box.name) != null ? _a : "\u672A\u5206\u7C7B"
      };
    });
    this.cardBodyCache.clear();
    for (const card of this.cards) {
      const file = this.app.vault.getFileByPath(card.filePath);
      if (file)
        this.cardBodyCache.set(card.id, await this.storage.getCardBody(file));
    }
  }
  scheduleRefresh() {
    if (Date.now() < this.suppressAutoRefreshUntil)
      return;
    if (this.refreshTimer)
      window.clearTimeout(this.refreshTimer);
    this.refreshTimer = window.setTimeout(() => {
      void this.refreshCards().then(() => this.refreshViews());
    }, 120);
  }
  suppressAutoRefresh(ms = 700) {
    this.suppressAutoRefreshUntil = Math.max(this.suppressAutoRefreshUntil, Date.now() + ms);
  }
  sortCards(cards) {
    const sorted = [...cards];
    switch (this.settings.sortMode) {
      case "created-asc":
        return sorted.sort((a, b) => a.created - b.created);
      case "updated-desc":
        return sorted.sort((a, b) => b.updated - a.updated);
      case "title-asc":
        return sorted.sort((a, b) => a.title.localeCompare(b.title, "zh-Hans-CN"));
      case "created-desc":
      default:
        return sorted.sort((a, b) => b.created - a.created);
    }
  }
  searchCards(query) {
    const normalized = query.trim().toLowerCase();
    if (!normalized)
      return this.cards;
    return this.cards.filter((card) => {
      var _a;
      const body = (_a = this.cardBodyCache.get(card.id)) != null ? _a : "";
      return card.title.toLowerCase().includes(normalized) || card.boxName.toLowerCase().includes(normalized) || card.tags.some((tag) => tag.toLowerCase().includes(normalized)) || body.toLowerCase().includes(normalized);
    });
  }
  makeEmbed(card, sourcePath) {
    const file = this.app.vault.getFileByPath(card.filePath);
    const link = file ? this.app.metadataCache.fileToLinktext(file, sourcePath, true) : card.filePath.replace(/\.md$/i, "");
    return `![[${link}]]`;
  }
  async openWorkbench() {
    var _a;
    const leaf = (_a = this.app.workspace.getLeavesOfType(VIEW_TYPE_HEPTACARD)[0]) != null ? _a : this.app.workspace.getRightLeaf(false);
    if (!leaf)
      return;
    await leaf.setViewState({ type: VIEW_TYPE_HEPTACARD, active: true });
    this.app.workspace.revealLeaf(leaf);
  }
  async openWorkbenchForCard(card) {
    var _a;
    const leaf = (_a = this.app.workspace.getLeavesOfType(VIEW_TYPE_HEPTACARD)[0]) != null ? _a : this.app.workspace.getRightLeaf(false);
    if (!leaf)
      return;
    await leaf.setViewState({ type: VIEW_TYPE_HEPTACARD, active: true });
    const view = leaf.view;
    if (view instanceof HeptaCardWorkbenchView) {
      await view.revealCard(card.id);
    }
    this.app.workspace.revealLeaf(leaf);
  }
  async openCardInNewTab(card, mode = "live") {
    const file = this.app.vault.getFileByPath(card.filePath);
    if (!file) {
      new import_obsidian4.Notice("\u5361\u7247\u6587\u4EF6\u4E0D\u5B58\u5728");
      return;
    }
    const leaf = this.app.workspace.getLeaf("tab");
    await leaf.openFile(file, { active: true, state: this.getMarkdownOpenState(mode) });
    this.app.workspace.revealLeaf(leaf);
  }
  getMarkdownOpenState(mode) {
    if (mode === "reading")
      return { mode: "preview" };
    return { mode: "source", source: mode === "source" };
  }
  async promptCreateCard() {
    await this.openWorkbench();
    const leaf = this.app.workspace.getLeavesOfType(VIEW_TYPE_HEPTACARD)[0];
    const view = leaf == null ? void 0 : leaf.view;
    if (view instanceof HeptaCardWorkbenchView) {
      await view.createCard();
    }
  }
  async postProcessMarkdown(el, ctx) {
    await this.embedRenderer.process(el, ctx);
  }
  refreshViews() {
    this.app.workspace.getLeavesOfType(VIEW_TYPE_HEPTACARD).forEach((leaf) => {
      const view = leaf.view;
      if (view instanceof HeptaCardWorkbenchView)
        view.refresh();
    });
  }
  registerCardRefreshHooks() {
    const onCardFileChange = (file) => {
      if (file instanceof import_obsidian4.TFile && this.storage.isCardFile(file)) {
        this.scheduleRefresh();
      }
    };
    this.registerEvent(this.app.vault.on("modify", onCardFileChange));
    this.registerEvent(this.app.vault.on("create", onCardFileChange));
    this.registerEvent(this.app.vault.on("delete", onCardFileChange));
    this.registerEvent(this.app.vault.on("rename", onCardFileChange));
    this.registerEvent(this.app.metadataCache.on("changed", (file) => {
      if (this.storage.isCardFile(file))
        this.scheduleRefresh();
    }));
    this.registerEvent(this.app.metadataCache.on("resolved", () => this.scheduleRefresh()));
  }
  async openReference(notePath, lineNumber) {
    const file = this.app.vault.getFileByPath(notePath);
    if (!file) {
      await this.app.workspace.openLinkText(notePath, "", false);
      return;
    }
    const leaf = this.app.workspace.getLeaf(false);
    await leaf.openFile(file);
    await this.app.workspace.revealLeaf(leaf);
    if (typeof lineNumber !== "number")
      return;
    const view = leaf.view;
    if (view instanceof import_obsidian4.MarkdownView) {
      const line = Math.max(0, lineNumber - 1);
      view.editor.setCursor({ line, ch: 0 });
      view.editor.scrollIntoView({ from: { line, ch: 0 }, to: { line, ch: 0 } }, true);
    }
  }
  setupFolderHiding() {
    this.registerEvent(this.app.workspace.on("file-menu", (menu, file) => {
      if (!this.settings.folderHidingEnabled)
        return;
      if (!(file instanceof import_obsidian4.TFolder) || !file.path)
        return;
      const hidden = this.settings.hiddenFolderPaths.includes(file.path);
      menu.addItem((item) => {
        item.setTitle(hidden ? "\u53D6\u6D88\u9690\u85CF\u6587\u4EF6\u5939" : "\u9690\u85CF\u6587\u4EF6\u5939").setIcon(hidden ? "eye" : "eye-off").onClick(() => hidden ? this.showFolder(file.path) : this.hideFolder(file.path));
      });
    }));
    this.registerEvent(this.app.workspace.on("layout-change", () => this.applyHiddenFolders()));
    this.registerEvent(this.app.vault.on("rename", () => window.setTimeout(() => this.applyHiddenFolders(), 100)));
    this.registerInterval(window.setInterval(() => this.applyHiddenFolders(), 1500));
  }
  async hideFolder(path) {
    const normalized = (0, import_obsidian4.normalizePath)(path);
    if (!this.settings.hiddenFolderPaths.includes(normalized)) {
      this.settings.hiddenFolderPaths.push(normalized);
      await this.saveSettings();
    }
    this.applyHiddenFolders();
    new import_obsidian4.Notice(`\u5DF2\u9690\u85CF\u6587\u4EF6\u5939\uFF1A${normalized}`);
  }
  async showFolder(path) {
    const normalized = (0, import_obsidian4.normalizePath)(path);
    this.settings.hiddenFolderPaths = this.settings.hiddenFolderPaths.filter((item) => item !== normalized);
    await this.saveSettings();
    this.applyHiddenFolders();
    new import_obsidian4.Notice(`\u5DF2\u6062\u590D\u663E\u793A\uFF1A${normalized}`);
  }
  applyHiddenFolders() {
    const hiddenPaths = this.settings.folderHidingEnabled ? this.settings.hiddenFolderPaths : [];
    document.querySelectorAll(".heptacard-folder-hidden").forEach((el) => el.removeClass("heptacard-folder-hidden"));
    if (!hiddenPaths.length)
      return;
    document.querySelectorAll(".workspace-leaf-content[data-type='file-explorer'] [data-path], .nav-folder[data-path], .nav-file[data-path]").forEach((el) => {
      const path = el.dataset.path;
      if (!path)
        return;
      if (hiddenPaths.some((hidden) => path === hidden || path.startsWith(`${hidden}/`))) {
        el.addClass("heptacard-folder-hidden");
      }
    });
  }
};
var HeptaCardSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "cardbox" });
    new import_obsidian4.Setting(containerEl).setName("\u5361\u7247\u5B58\u50A8\u6587\u4EF6\u5939").setDesc("\u5361\u7247\u4F1A\u4F5C\u4E3A\u72EC\u7ACB Markdown \u6587\u4EF6\u5B58\u50A8\u5728\u8FD9\u91CC\u3002").addText(
      (text) => text.setValue(this.plugin.settings.cardsFolder).onChange(async (value) => {
        this.plugin.settings.cardsFolder = (0, import_obsidian4.normalizePath)(value || "_CardBox/Cards");
        await this.plugin.storage.ensureFolders();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("\u5361\u7247\u76D2\u6587\u4EF6\u5939").setDesc("\u7528\u4E8E\u5B58\u653E\u5361\u7247\u76D2\u76F8\u5173\u7684\u5185\u90E8\u6570\u636E\u3002").addText(
      (text) => text.setValue(this.plugin.settings.boxesFolder).onChange(async (value) => {
        this.plugin.settings.boxesFolder = (0, import_obsidian4.normalizePath)(value || "_CardBox/Boxes");
        await this.plugin.storage.ensureFolders();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("\u5D4C\u5165\u6837\u5F0F").addDropdown((dd) => {
      dd.addOption("card", "\u5361\u7247");
      dd.addOption("compact", "\u7D27\u51D1");
      dd.addOption("panel", "\u9762\u677F");
      dd.setValue(this.plugin.settings.embedStyle);
      dd.onChange(async (value) => {
        this.plugin.settings.embedStyle = value;
        await this.plugin.saveSettings();
        this.plugin.refreshViews();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("\u61D2\u52A0\u8F7D").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.lazyLoad);
      toggle.onChange(async (value) => {
        this.plugin.settings.lazyLoad = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("\u663E\u793A Info \u9762\u677F").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.showInfoPanel);
      toggle.onChange(async (value) => {
        this.plugin.settings.showInfoPanel = value;
        await this.plugin.saveSettings();
        this.plugin.refreshViews();
      });
    });
    containerEl.createEl("h3", { text: "\u9884\u89C8\u89C6\u56FE\u5927\u5C0F" });
    this.addPreviewScaleSetting(containerEl, "\u5C0F\u89C6\u56FE\u5927\u5C0F", "previewSmallScale");
    this.addPreviewScaleSetting(containerEl, "\u4E2D\u89C6\u56FE\u5927\u5C0F", "previewMediumScale");
    this.addPreviewScaleSetting(containerEl, "\u5927\u89C6\u56FE\u5927\u5C0F", "previewLargeScale");
    this.addPreviewTitleSizeSetting(containerEl);
    containerEl.createEl("h3", { text: "\u6587\u4EF6\u5939\u9690\u85CF" });
    new import_obsidian4.Setting(containerEl).setName("\u542F\u7528\u6587\u4EF6\u5939\u9690\u85CF").setDesc("\u5F00\u542F\u540E\uFF0C\u6587\u4EF6\u5939\u53F3\u952E\u83DC\u5355\u4F1A\u51FA\u73B0\u201C\u9690\u85CF\u6587\u4EF6\u5939\u201D\u3002\u8FD9\u53EA\u5F71\u54CD\u6587\u4EF6\u6D4F\u89C8\u5668\u663E\u793A\uFF0C\u4E0D\u4F1A\u79FB\u52A8\u6216\u5220\u9664\u6587\u4EF6\u3002").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.folderHidingEnabled);
      toggle.onChange(async (value) => {
        this.plugin.settings.folderHidingEnabled = value;
        await this.plugin.saveSettings();
        this.plugin.applyHiddenFolders();
      });
    });
    const hiddenList = containerEl.createDiv({ cls: "heptacard-settings-hidden-list" });
    if (!this.plugin.settings.hiddenFolderPaths.length) {
      hiddenList.createDiv({ cls: "setting-item-description", text: "\u6682\u65E0\u9690\u85CF\u6587\u4EF6\u5939\u3002" });
    } else {
      this.plugin.settings.hiddenFolderPaths.forEach((path) => {
        new import_obsidian4.Setting(hiddenList).setName(this.displayHiddenPath(path)).addButton((button) => {
          button.setButtonText("\u6062\u590D\u663E\u793A").onClick(async () => {
            await this.plugin.showFolder(path);
            this.display();
          });
        });
      });
      new import_obsidian4.Setting(hiddenList).setName("\u5168\u90E8\u6062\u590D").addButton((button) => {
        button.setButtonText("\u6062\u590D\u6240\u6709\u6587\u4EF6\u5939").onClick(async () => {
          this.plugin.settings.hiddenFolderPaths = [];
          await this.plugin.saveSettings();
          this.plugin.applyHiddenFolders();
          this.display();
        });
      });
    }
  }
  displayHiddenPath(path) {
    if (path === "_HeptaCards")
      return "_CardBox/Cards\uFF08\u65E7\u76EE\u5F55\u517C\u5BB9\uFF09";
    if (path === "_HeptaCardBoxes")
      return "_CardBox/Boxes\uFF08\u65E7\u76EE\u5F55\u517C\u5BB9\uFF09";
    return path;
  }
  addPreviewScaleSetting(containerEl, name, key) {
    const valueEl = document.createElement("span");
    valueEl.setText(`${this.plugin.settings[key]}%`);
    valueEl.addClass("heptacard-setting-value");
    new import_obsidian4.Setting(containerEl).setName(name).setDesc("\u8C03\u6574\u53F3\u4FA7\u5361\u7247\u9884\u89C8\u533A\u5BF9\u5E94\u89C6\u56FE\u7684\u6574\u4F53\u5C3A\u5BF8\u3002").addSlider((slider) => {
      slider.setLimits(80, 140, 5).setValue(this.plugin.settings[key]).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings[key] = value;
        valueEl.setText(`${value}%`);
        await this.plugin.saveSettings();
        this.plugin.refreshViews();
      });
    }).controlEl.appendChild(valueEl);
  }
  addPreviewTitleSizeSetting(containerEl) {
    const valueEl = document.createElement("span");
    valueEl.setText(`${this.plugin.settings.previewTitleSize}px`);
    valueEl.addClass("heptacard-setting-value");
    new import_obsidian4.Setting(containerEl).setName("\u5F53\u524D\u89C6\u56FE\u5361\u7247\u6807\u9898\u5B57\u53F7").setDesc("\u8C03\u6574\u53F3\u4FA7\u5361\u7247\u9884\u89C8\u533A\u6807\u9898\u7684\u5B57\u4F53\u5927\u5C0F\u3002").addSlider((slider) => {
      slider.setLimits(14, 32, 1).setValue(this.plugin.settings.previewTitleSize).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.previewTitleSize = value;
        valueEl.setText(`${value}px`);
        await this.plugin.saveSettings();
        this.plugin.refreshViews();
      });
    }).controlEl.appendChild(valueEl);
  }
};
